apiVersion: v1
kind: Namespace
metadata:
  name: smb-csi
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: smb-csi
  namespace: flux-system
spec:
  interval: 5m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smb-csi
  namespace: smb-csi
spec:
  interval: 5m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: csi-driver-smb
      sourceRef:
        kind: HelmRepository
        name: smb-csi
        namespace: flux-system
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-smb-sc
provisioner: smb.csi.k8s.io
parameters:
  source: //nixnas/k8s
  csi.storage.k8s.io/provisioner-secret-name: csi-smb-secret
  csi.storage.k8s.io/provisioner-secret-namespace: smb-csi
  csi.storage.k8s.io/node-stage-secret-name: csi-smb-secret
  csi.storage.k8s.io/node-stage-secret-namespace: smb-csi
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverinfo # recuired to prevent date corruption
