apiVersion: v1
data:
    password: ENC[AES256_GCM,data:tl3WpT/GrU2UILvJNIg+/CMg6L0ElBgmZZiYcMngoDNelVdYFpu1/p2Nov47nCXR,iv:FvLXCMMXKizj76Ye+UQucf16AGAuA/pWv5GsEi6D6wo=,tag:i1Ak+e2N0d0ZEOSVl+1hvQ==,type:str]
    username: ENC[AES256_GCM,data:U4R9XQ==,iv:y8KokIpSQbjsaakqgGKmTLPjfOFNAzwnaVTDrrz5I9w=,tag:N4jHiWbhzNBUW/zq7Sj7Kw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: csi-smb-secret
    namespace: smb-csi
sops:
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidVZLMFR2SXUwc3RhaCtx
            bS9xalhqczA3bDRPNm9vL3o4K09oQmhRSUZJCm5MWnRGWVlVVVJjNUIzSWR0dU5E
            TVZaU1BzUVBxWVZTR25NV0dmY3J4RjAKLS0tIEJCMEU3SDhKTThTbHRCTCtabUl3
            bUV2QWxOMVF0aXhNem1BVG1JUmExeVkKE7nxbg8E+jK9PhFil/s+dh9LN9v7P3ZZ
            RyUt5xN63IsAnay9ohrrP0V3GixYSn40NzA67cQsXLC6V6lj7uXh8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-08T16:07:51Z"
    mac: ENC[AES256_GCM,data:o0m93/I+rDCcB5GZxKe4WNsVt5aCoBfoPq7KCJEkUbpiaK+XHtLTbn7fHqBNulGtp7kVkZuK9rFLsVtzzRwdPqGAS8RuH/+dlK9iYz+o/UxXUE8veDA206eBnX4JvsrhzlZnEaadAT5U2vYSdwFjBJfDN+PdBBF6ZeKj/yRLS3E=,iv:o3fQcOn7yAMFZd5bmwn092e7707IxD0vpQligHg3kos=,tag:Ma5dvvISH0ESVbfubUFhgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
