apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/immich
  # - ingressConfig.yaml
  - immich-postgresql.yaml

patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
