apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on
              # the manifest
              image: renovate/renovate:41.152.9
              args:
                - JvandeLocht/fluxcd
                - JvandeLocht/nixos
              # Environment Variables
              # env:
              #   - name: LOG_LEVEL
              #     value: debug
              #   - name: RENOVATE_FORCE # Force reset
              #     value: '{"schedule": ["at any time"]}'
              #   - name: RENOVATE_RECREATE_CLOSED # Recreate closed PRs
              #     value: "true"
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never
