apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:QfuHvbU=,iv:tfnMGRfydB+FbrqG/OVeN54NUiyWqz3OE7506j7zYao=,tag:Rcb41qM205jA0G7NfN1vtg==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:gdm1cY8KFMoWz+V1oWFTxipw/B2E9O/bJNa/Fc9TQonmPg==,iv:V5nb0NU/iC0LHn2lAhsy0phfyaT3Pp3PoucOSeGHj5s=,tag:wQtSyTjPyEFwi1mkFYXlQg==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:AVq3MLf4,iv:FL+Q6fQ+o6ejT39z80uE0aVicqgvUvio/e8vK6FLzUQ=,tag:ABsFSp/SgAwfL4Ua4QOWxw==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:EwfgzTIRdoMJAlNelI8weYbNMEioLrz2uQNdt69fCj1INMomUZBE214sYmammwNsRvkwi/zy6OsIP2D4OzuRxUfZ1h216QpvaSX650O8Yo+aXN8UCbpxbAvkUgYZ,iv:snKCxSFVJpVTffVfg+uAMc62BKM7VCaK+qMuYTVNSI8=,tag:sbARlKkx2RQvm1yhyJbHlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaUprb2xQWVdvNWtKMW1X
            NFFjeldDQzU4d1pPTXc1RnpZSURTVnhMaHk4CnhySlB1c2RHLzNnSkp4S3V0bklk
            NzUrRWlWQWhSbzdLeW1wWGtaNEFwQjgKLS0tIHlmQmRGdUZmSDZGSWdSNkZKK1h5
            QkhzazJ2MFh0RDlaS0x1V0Q0aGRnR1EK8xNRPLAGEyApGckoKq78yUZYbLi1FJBB
            T0FV008pvT5OLQpjmyL0kGub77x8RG9st336vFR0o9c+a4Yo+LsJNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T12:36:40Z"
    mac: ENC[AES256_GCM,data:K2xN4tEvg1n9Ua9enh7vcGzNC/di0ZlPgpquA4xEieXCWOYQ9kV1f5FTEGpH5831aejKRt8vyURgRUr5uGzxVTl1eNd4TzOl4ozE3TdqEgQSDeAx0CvYktNoAhEalF/3Vt6cHorXGnLyrbptKtDZvLKXsLTZqMAiAz2jXfykIE0=,iv:Vba03AJ8osX/m/ZBAARyJpEZb+DmixOy7I/LiJHMnR4=,tag:IsJoB5rr46TZbenQ536bFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
