---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vmware-tanzu
  namespace: velero
spec:
  interval: 24h
  url: https://vmware-tanzu.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/kubernetes-csi/external-snapshotter
  ref:
    semver: "6.3.2"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: velero
      version: "10.0.1"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 500m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 512Mi
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    configuration:
      # features: EnableCSI
      backupStorageLocation:
        - name: minio
          provider: aws
          bucket: velero
          default: "true"
          config:
            s3Url: http://192.168.178.58:9000
            region: minio
            s3ForcePathStyle: "true"
          credential:
            # name of the secret used by this backupStorageLocation.
            name: velero-secret
            # name of key that contains the secret data to be used.
            key: cloud
      volumeSnapshotLocation:
        - name: minio
          provider: aws
          bucket: velero
          config:
            region: minio
          credential:
            # name of the secret used by this backupStorageLocation.
            name: velero-secret
            # name of key that contains the secret data to be used.
            key: cloud
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
---
