apiVersion: v1
kind: Secret
metadata:
    name: gitea
    namespace: gitea
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:69x7+xIlC5pfYvEo4+AwudyYICyUYtXfCxWsHL01ckUJiQ==,iv:uPQEb9Qi4VamdAx3zS6jH8RABrkzExWiNJbvpRfLkDU=,tag:L0vM8jRW5BS53+OuJFVgKQ==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:9KJ5Aoth,iv:gjePaP5+XYf75Am0IhLpxiYlJCi6PWYVmHZVNLMNjWo=,tag:gMVgCjP14v9CavnsJGOpQw==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:aMsDC1psYmciFHX43Qcm,iv:Z2Avev0xqIzunq24kgXA4OrmdcELTftVRq3j3POcNxg=,tag:sRSAbpPOuudtKzX1cQi9nw==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:sSIz4Bip,iv:FH5YUlqS0aD35jdT8as3C94GeerBwTIePYlMefacYHc=,tag:aCfMH8u+IKhVlG/r6i9q9Q==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:Jo0r,iv:879apiTLOb4Iy8wwy4IOYJIEGtxBjkghnInMt/QH340=,tag:Q9oawf9kHdCx+nH6oRrBYA==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:YZwYzf9yhA==,iv:w11SMSQVW4ay02datOrObYbiN5G2WZrupsaV8vmSxfk=,tag:ZO33oQiM1GrXVKL7LMLowQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YTRDU1B0OUVuOGJYb3lq
            RndoM3gzeGpjQ2M5WVNuMHE4VkFLZXNlVUZvCmdidmU3VXRyVEtWZElVdVZ4MXhu
            dUJSaDAyQmhqeWg3eUo0NWNqSFlzYUEKLS0tIGwxYmUwdFQwTDJmeUdBNXdMQkNo
            NUN3dVNqWDlnckNDRnFWMk9YNFBDUzgK/+WC4RqN83FRjJ/uNtHQitT/skvU/QBi
            qTeXVwOwUXOl2j81xrFc/ip90+v1wXpF8N1ESsQpj97ktepPy2b40Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T08:45:10Z"
    mac: ENC[AES256_GCM,data:3L80XqChm2wszM+Rqvqwam9j571TLSPEnzmXz1roGFSWE1SIax1hOLSLdRgxn6wIQBaaNWRO2WLtASmtt79FyZn74a8qLkdwBE+FN05nk67pMnAgAvk6HzFcXsuELGcB1oTjQ4R+r04wN1UEfGcubqEQAIrP97XoUZALtFZjktE=,iv:quoAPvZPPewqqnIdNkiMm54OiB6jyoNi+/eSkCcCzjw=,tag:Wfy+Jm3Rb7GYFwZg7lS1zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
