apiVersion: v1
data:
    redis-password: ENC[AES256_GCM,data:M6LeiLprZnvsvumlTVpdKhM1Nz4gAOR7pq2GgxAYEJylkuBmwZaWUkMM/Fm/C2MhxnsQ5cl7GwnfMcjUhZmqjQ==,iv:MmU2PW/h9GzCGbqYQAcAbNu6Lo5+gO/c1LFD/CLWl/Q=,tag:QwmXfL6pwECULLGhEDYJfg==,type:str]
kind: Secret
metadata:
    annotations:
        meta.helm.sh/release-name: gitea
        meta.helm.sh/release-namespace: gitea
    labels:
        app.kubernetes.io/instance: gitea
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: redis
        app.kubernetes.io/version: 7.2.5
        helm.sh/chart: redis-19.6.2
        helm.toolkit.fluxcd.io/name: gitea
        helm.toolkit.fluxcd.io/namespace: gitea
    name: gitea-redis
    namespace: gitea
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTTZUZmxxcnhWY2RST1Jy
            UU43OGJIZmdSUU5vZklXcDViV3JFb296ZFdnCmNlWm1QdWNaTWlrVldtZlh3bjYr
            YUdPdHlEc3VZeUs5enE5clNGblpNRG8KLS0tIFlNem5BV3dLTDdNUXJTd3JlNzRQ
            bzZSalhLRHEvcW94UXpKNUVRNzhMVkEKNO8bN3B7Dgo522icceeZ/yAsV9pYrVYt
            q1j0g1RaLze1WznYKnKQZD18E5nkDD6M0cK+crhRBKUhA8tzN4/N8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T08:57:15Z"
    mac: ENC[AES256_GCM,data:WTQjCJt6nVyfcCsUi9tUswXXj4LfX1s8tkA+hMeDQ6JZI+guYmxrA1IElREEwwJ7cTjS4K6Jpla65PYdNL/qFK0lC6LouK+Rhq31hCWXPXHLTlJIC2aR5UQMnLZXsZ0draAV09NRa0fbp0hRxa68513bY7WtwgaSxF/88kl5toY=,iv:4xPVvoYm7Kgtvo6wN03CPUZHYeaJa9/Hj3FhlvawN2o=,tag:TfswqQnQxsDh4sRlb4qK2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
