apiVersion: v1
data:
    email: ENC[AES256_GCM,data:Mqx7RLSnQEpKCZQ4pLzH80u/lMm5yg3U,iv:zXeSy7LJq9Rgk7vXMIcdszQnwYJ1crpg/uSlgH3IPkQ=,tag:M3KNRbW3OOkPrn3mtGKuuw==,type:str]
    password: ENC[AES256_GCM,data:6RxxVxg3I/+ERn+DH3ROVsDJLkW60QmdqUflv9V/giQtZ1NZxAVbmm2DjAKVoOqdIP2+ir/4Tf8HK0yZ,iv:EfhuBEk3IgiURzXCZz8nkxBdT8abBTok2GeGxjTCacg=,tag:I410jhsmJED+ynPOv5fiiQ==,type:str]
    username: ENC[AES256_GCM,data:IERm5w==,iv:LZJKVwnPaL4JcFByArJd1sl6KePGopMGsC5ABJXkP5k=,tag:gc3Shn6aY2cudqjI/VqXXQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitea-admin-secret
    namespace: gitea
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: gitea
        meta.helm.sh/release-namespace: gitea
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRGVIS3NLcHhDVStHOVZF
            dkpEL1loclNLeGdCWFhyVWp1NVhRVGFMQWdZCnY0bzZVZEh6WEFRVGM2dVg1NUx4
            TEExZTFlZ1Y0YWtFRk9RcHZHU2g3cDQKLS0tIFhqRm52OU5TcEZ3aHl3ejlNRmJY
            V0RwcUZkMUxLUWRza2dVYzRzTnZsd2MKTJm6yUAJ1UBj0cskW8eWe1lVgx3MrOp9
            /sqfSoX4hwNdoiq0oPQV0890qCdQspzm7VNCtnxIqes6AvITtPH46Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-05T21:14:56Z"
    mac: ENC[AES256_GCM,data:hYQQ00KD1JjwGkSKtm5TTyM58sIUFBBcf5uo3DSkDRuLTYFmWC/0lQ1QyvH9t2MrBZ1d9UcftQdCH8RYztl4uomzXYvwYAijySHOEU+cAYhQvtkKDj1ywDvGTHVv2fAwjNNlwosJgPR9sqrnQfQ9QhaH7q4EsSFuxrmsT9ZnKDw=,iv:v2DhF+2EMN/KuAcYhXGEm53mWRv/otIiIrGDSK5x7w0=,tag:tSjCae/8/J1bx5xXnN3j7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
