apiVersion: v1
kind: Secret
metadata:
    name: gitea-postgresql-claim
    namespace: gitea
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:WLmEDaV/MyitlVm/Gi6f66KK40iNMfvatFDpCnTj1vXvSes=,iv:PSWMEXdBuRNm0mj1R3TtNK1yRk2QbiNfevB4paE7i54=,tag:NKAQ+oQi2e3WOC9cJZBLaQ==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:8RFot81O,iv:55osTjedgJHX2cXN4dfO3FXXSALqi8VJDL9kZtzHJhg=,tag:vP1InX/CwqCFXOmdXtYcDw==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:MbJf62sGcP6vtu5bXR5X,iv:xlV7xHDApjwKJ0NGAuOo2CB/vr8+S93LR/gH1nGvPIc=,tag:KP32QlNV7agIYFIb6uhxhg==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:glc5V7bX,iv:JrT1pD15+jPe6jerCY7hOwdm0Uo0fspysVuqX2dzyPA=,tag:YZlRMV1QuxfvZXTKZKwE+w==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:WfS/,iv:k3BKdRDMke+Hhf4JH7K34YVVkxfQGVDxfNQy4R9lh1A=,tag:/hdI/m52NXhK/wjrmqSt2w==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:ExVbUUMR0g==,iv:tQD1UZzaYmPPisu5CZQeYeMCyoV5bUlu71TKbYW6duU=,tag:nRSgpU5SRyp6XG9g2Jty+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUjlhdjM2MnBVUGh1K2tZ
            VWVIcHZjU3VKakpoREJlUkJEMUdGYlFFeldnCmw2WHZ4SGpCS0pRVkFNZStKRUM2
            WFp5Z3VCbGZ3Y0wxL1NQaUlodFdOSGsKLS0tIDdIVjhyWEVPWjl2MGNab3R0RHFa
            L1pTYWJOMXI2Z1JNNUZXS1ExWDVBU2cKGU9QPVBIoX6BNbQSgok/uLujQqsWMWTL
            Yh6FbMkyiSQ5f9zHNURbQEHpXH6EFmXlGCDHwYaf8e69Ti8UlkxVHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T08:45:10Z"
    mac: ENC[AES256_GCM,data:WkvFxuIl+FE5VgWofVWgYgAAHrr4OjgiZmjUUhHvy5+zvr2uAPVcRLgHIw5xRpNLtFUW7LsROKPFCu33h1A1fdDqhBmC3kEdmJAtB6Op0TKlivoaqYVcGkJCH98gpa/7bQ8DqoFHVvoz1eKiSn8VoXVMbpsTp1AiEaL3NTW90ZY=,iv:KIImevD8deFCw1xIXoLyFQ6ftLUWj9rUVbY2vfVU7Vc=,tag:wDzqytT+lk3pcOo/uFgA0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
