apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/gitea
  - ingressConfig.yaml
  - gitea-admin-secret.yaml
  - gitea-postgresql.yaml
  - gitea-claim-secret.yaml
  - gitea-postgresql-claim-secret.yaml

# patches:
#   - path: patch.yaml
#     target:
#       kind: HelmRelease
