apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/gitea
  - ingressConfig.yaml
  - gitea-admin-secret.yaml
  - gitea-postgresql.yaml
  - gitea-redis.yaml

patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
