---
apiVersion: v1
kind: Namespace
metadata:
  name: blocky
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: truecharts
  namespace: blocky
spec:
  type: "oci"
  interval: 5m0s
  url: oci://tccr.io/truecharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 30m
  chart:
    spec:
      chart: blocky
      version: "15.2.x"
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: blocky
      interval: 12h
  values:
    prometheus:
      enable: true
      path: /metrics
    blockyConfig:
      upstream:
        default:
          - 1.1.1.1
          - 9.9.9.9  
      ports:
        dns: 53
        http: 4000
      customDNS:
        customTTL: 1h
        filterUnmappedTypes: true
        mapping:
          proxmox.lan: 192.168.178.40
        # zone: |
        #   $ORIGIN example.com.
        #   www 3600 A 1.2.3.4
        #   @ 3600 CNAME www
        # rewrite:
        #   home: lan
        #   replace-me.com: with-this.com

      # blocking:
      #   denylists:
      #     ads:
      #       - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      #   clientGroupsBlock:
      #     default:
      #       - wds
