apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emqx
  namespace: homeassistant
spec:
  interval: 5m0s
  url: https://repos.emqx.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: homeassistant
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: emqx
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: homeassistant
      interval: 12h
  values:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
