apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:UT7T,iv:01SFcidpeTO70XtSDEbaLZwtOvgat2Ey11qYBipMMAI=,tag:nRs7xRPZoPLovUMbFVfldA==,type:str]
    admin-token: ENC[AES256_GCM,data:DKOX,iv:IpZO4vuej11E0XHrFJzZC/VnPlUMFAljy68lKLQp1Lk=,tag:4UdMpUDVB83/Hgzz1uWA8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL0FnYlY3a1N6WTVlUUVx
            d3FPSHNzZXlSTGhHNWFraTFCekl6U3k5aW1RCjM2UjFjdHdTT3FzbzNXT2hpUnJI
            ZXN4Mk9DQitrS3VwT1ZRNFFCb25XRFkKLS0tIGFkejZDcnBDdXV4UXNQR3ovYWJ4
            bzV6cVZFRDh2OUZlRjlwY2JtQW5mZDgKgW0A3cWRKyJKkKExsqtCj3U950yHMSkw
            7PGTr7LzkDWl8FmtugUKlfHikQEUUdv+wtn2t/gNws9AwosVQ7/eFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T22:04:15Z"
    mac: ENC[AES256_GCM,data:nyqr0bq35JDfniWTiD3XoE3ipW91MUZOWjTVzm0EzF+0j3ej+Jzq+uJ4xXtvFwbBFllFpBgbT5V1lTU/YQFH4FpiLwXkfV5l+323rRdbRXIqOpD7v8WSzbuzBHtZ4uX++ZTWTmPa+ULuWDD2M/nLxxpT06Y1uYP5nwQrA4saim0=,iv:o0lYSmyMdNwFHEH4jDc94dTuZTgUY8kPP3Z83WY1VA0=,tag:jDsER8NBb/4S125qftDU9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
