apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zigbee2mqtt
  namespace: homeassistant
spec:
  interval: 5m0s
  url: https://charts.zigbee2mqtt.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: homeassistant
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: zigbee2mqtt
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: homeassistant
      interval: 12h
  values:
    statefulset:
      securityContext:
        privileged: false
        capabilities:
          add: []
      storage:
        enabled: true
        storageClassName: longhorn
        size: 1Gi
      resources:
        requests:
          memory: 600Mi
          cpu: 200m
        limits:
          memory: 600Mi
          cpu: 200m
    service:
      type: ClusterIP
      port: 8080
    zigbee2mqtt:
      mqtt:
        # -- Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
        server: "mqtt://emqx.homeassistant.svc.cluster.local:1883"
      serial:
        port: tcp://192.168.178.29:6638
        baudrate: 115200
      advanced:
        transmit_power: 20
  valuesFrom:
    - kind: Secret
      name: zigbee2mqtt-secret
      valuesKey: values.yaml
