apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager/
  - letsencrypt-production-cluster-issuer.yaml
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
