apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik
  namespace: metallb-system
spec:
  addresses:
  - 192.168.178.151/32
  serviceAllocation:
    priority: 50
    namespaces:
      - traefik
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: unbound
  namespace: metallb-system
spec:
  addresses:
  - 192.168.178.152/32
  serviceAllocation:
    priority: 50
    namespaces:
      - unbound

