apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
spec:
  template:
    spec:
      containers:
        - image: favonia/cloudflare-ddns:1.10.1
          name: cloudflare-ddns
