apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  # namespace: flux-system
spec:
  template:
    spec:
      containers:
        - env:
          image: favonia/cloudflare-ddns:1.10.1
