apiVersion: v1
kind: Secret
metadata:
    name: gitea-shared-storage
    namespace: forgejo
    annotations:
        meta.helm.sh/release-name: forgejo
        meta.helm.sh/release-namespace: forgejo
    labels:
        app.kubernetes.io/managed-by: Helm
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:yXTKOYhKZxfKqqK4AsrZXGq7U2kSwliISLu1tyx9W8gJNQA=,iv:gcVAYLwST0CTflcJlIRNOTumEQvE98zOvYKAHd8H8zc=,tag:6Xwrq+Ywdcz9h8wVW2XIqQ==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:Frxj7Xfa,iv:/q+f8gqPmvNKe85zlaZhJZWRgP8rkvCQgIOTh8+80TI=,tag:efsmOzKgI6w9mFzw8QfFPw==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:i1nZhb3+5aDoPZ118ey1,iv:fAveW6cZTOJDODdt3elY3QTJZ0e75TRr8JGIxV0Ykew=,tag:N5jWJ0YlGfBSmkAEq1/CFw==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:VdHtrckE,iv:0CjXOCGet4I49Nw9IH5buYcvdPzaNF9yfS8pjlHihSk=,tag:tCr7cHO7vrs/ABZgYKvftg==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:1LYi,iv:6SeJ0/g+oVZIRuibnk8mpGfVXbCzzXfkJY7+4TUyFkc=,tag:4j4zNzy8ZzdNmOefASaX2Q==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:/vPm2k7uUg==,iv:pJOptjYTihCBLnoiyJH5FcCLwrTMuZSqIBFg//ccGWk=,tag:3qaWicyhaApVUTi0U0Go8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNmdMblFvMHkxT1A4OWI3
            S01OcFpmSERhODJ2Z1NJMzRWdVl1bVgwT3dvClhnOS93U0owRGQvOWpzMTZSRGY4
            TE5zR3JtQjJqZHFKWFNzSk4vcXVralEKLS0tIGJ5clBQSjRsSUtENC9rTkZhMjB5
            aks5NXc4dFAycXBuWjRJdDVoM0U1NVkKgqnZChWwLilWg+vPuhxwLnBcPmw800Jm
            WdRr20w1D45uK55nJVCLWckwT4YZJooBZcGREXY3c67oCL5OhE+B7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T20:01:53Z"
    mac: ENC[AES256_GCM,data:ss4RuwmMCrPvKrxNkrmDJQtSpGKePxn8R/fCWWkGq9I4B069/yINJW7KLPQ6U2XLyYI2PnPVlI0amQoXUoLoozgXWMiiBcTAbdfmOI5F7DMPO3XZngZeeMbN4o9ikejPzzt00ZnUOls9PmEo5QjhwMg1+bd+FihwpADuk75DdAk=,iv:eR9Mj8el8NvdtPW7xCcpe2wlLdwQ9XxU7lWlReY/w7k=,tag:Q+AR6xYQ6CpwgJf4d6wi+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
