apiVersion: v1
kind: Secret
metadata:
    name: forgejo-postgres-cluster-1
    namespace: forgejo
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:DxV+F/leP4Jo4jiFwTF3lPRlxsOLyoFXGNQiqnHuuh7IIZQ=,iv:ekWJ9Ekm9SOo0UjybGs0dm6EwBJLWCrG6NSJtDfDM5Y=,tag:qw6LV+2dgQV8M3+mub6RQg==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:LtoWz4Vu,iv:loIt+PqwRtE06aJOuqfUj1O/YjERMbJsF2jSEbQD6xw=,tag:ABxmdGZYMuE024OfQ2ckMA==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:us5vVJoHDwb69J1GnTpt,iv:0IIfzBNP9BaqoL7kPTvgEeoqg955uoIljjLT7RR7KoE=,tag:tTO0YK1OAMhgiDCDTWLaxw==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:7+74bDMQ,iv:h6P3j3xsaWqIY/YPPQnrRnW0hUgWjRUWBQFq8z3D5TY=,tag:OfUJM7upuVea8dh7nBse3g==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:+M3l,iv:kEs1xnvKqN4MCukUSSZVFQsQ4IZatHjaLX89s94bUMM=,tag:d00zmFT6/jb49AMbuOJO7g==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:NBJ4cZi49A==,iv:ZkL8AKANxR2RfMJ5QvaQaXVQ9jaze/wHdo56mpyNx0g=,tag:pXdvymH2NGlSq75gdLxIYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbnpISDBTNzQvWEpkT2Fm
            a3NKS1VrSlY5R2EyeUZrTWtpQTZOcE0wMkFZClJ0Z1hkSG9rVjU3eUU2VmI2K3d2
            QTJtMWlkcnhkZlJhTEFZZUVpWG5JelkKLS0tIFJDWG5haG9mRzVzQy9ZRTEyTGlx
            R2RiYmZhYjdMMzN0TVlFZVBWMnFrZE0KQYMUAbcCQFxgH2MQ23K6CEIawJ1L6HFf
            4kBytoOaBF8ZLZqbKYqNXlKMh6qIcfmHfwv15gJOww/ZWuQho70e5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T10:22:03Z"
    mac: ENC[AES256_GCM,data:GEM9SwCcM43sencYlkxrmPpWYKWHRSSwXy4nFsB8C3Xp7+rfPoXaX0Rw6zG5LAY2Ji1yMoPRjMH75uDq7un9Tw/OX3LBI0WhcPszuDo8Zm2hhT+hFuDhXVihCunR9+PPb8YIKBkzbSyUW8YLxdGBcjmoGKT0nAcwpMKHCI1qkMM=,iv:SNTsMGaQSFIRJSzboeURpmCUYweisIBxW5ngBkt6coM=,tag:7GWYin828cNLmNE3dObz4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
