# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: svc-forgejo-headers
#   namespace: forgejo
# spec:
#   headers:
#     browserXssFilter: true
#     contentTypeNosniff: true
#     forceSTSHeader: true
#     stsIncludeSubdomains: true
#     stsPreload: true
#     stsSeconds: 15552000
#     customFrameOptionsValue: SAMEORIGIN
#     customRequestHeaders:
#       X-Forwarded-Proto: https
# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: forgejo-local
#   namespace: forgejo
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`forgejo.lan.vandelocht.uk`)
#       kind: Rule
#       services:
#         - name: forgejo-server
#           port: 2283
#       middlewares:
#         - name: svc-forgejo-headers
#   tls:
#     secretName: forgejo-lan-vandelocht-uk-production-tls
# ---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-lan-vandelocht-uk
  namespace: forgejo
spec:
  secretName: forgejo-lan-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "forgejo.lan.vandelocht.uk"
  dnsNames:
    - "forgejo.lan.vandelocht.uk"
