apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-lan-vandelocht-uk
  namespace: forgejo
spec:
  secretName: forgejo-lan-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "forgejo.lan.vandelocht.uk"
  dnsNames:
    - "forgejo.lan.vandelocht.uk"
