apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-vandelocht-uk
  namespace: forgejo
spec:
  secretName: git-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "git.vandelocht.uk"
  dnsNames:
    - "git.vandelocht.uk"
