
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo
  namespace: forgejo
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`forgejo.vandelocht.uk`)
      kind: Rule
      services:
        - name: forgejo-http
          port: 3000
      middlewares:
        - name: svc-forgejo-headers
  tls:
    secretName: forgejo-vandelocht-uk-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-vandelocht-uk
  namespace: forgejo
spec:
  secretName: forgejo-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "forgejo.vandelocht.uk"
  dnsNames:
  - "forgejo.vandelocht.uk"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: svc-forgejo-headers
  namespace: forgejo
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
