---
apiVersion: v1
kind: Namespace
metadata:
  name: actual
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actual
  namespace: actual
spec:
  interval: 5m0s
  url: https://beluga-cloud.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actual
  namespace: actual
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: actual
      sourceRef:
        kind: HelmRepository
        name: actual
        namespace: actual
      interval: 12h
  values:
    images:
      tag: "latest"


