---
apiVersion: v1
kind: Namespace
metadata:
  name: guacamole
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: guacamole
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: guacamole
  namespace: guacamole
spec:
  interval: 5m0s
  url: https://charts.beryju.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: guacamole
  namespace: guacamole
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: guacamole
      version: "1.4.1"
      sourceRef:
        kind: HelmRepository
        name: guacamole
        namespace: guacamole
      interval: 12h
  values:
    guacamole:
      settings:
        TOTP_ENABLED: "true"
    postgres:
      hostname: "guacamole-postgres-cluster-rw"
      port: "5432"
      database: "guacamole"
      user: "guacamole"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: guacamole-postgres-cluster
  namespace: guacamole
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  bootstrap:
    initdb:
      database: guacamole
      owner: guacamole
      secret:
        name: guacamole-cnpg

  storage:
    # storageClass: "longhorn-crypto-per-volume"
    size: 4Gi
  monitoring:
    enablePodMonitor: true
