---
apiVersion: v1
kind: Namespace
metadata:
  name: guacamole
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: guacamole
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: guacamole
  namespace: guacamole
spec:
  interval: 5m0s
  url: https://charts.beryju.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: guacamole
  namespace: guacamole
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: guacamole
      version: "1.4.1"
      sourceRef:
        kind: HelmRepository
        name: guacamole
        namespace: guacamole
      interval: 12h
  values:
    postgres:
      hostname: "postgresql"
      port: "5432"
      database: "guacamole"
      user: "guacamole"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: guacamole
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: postgresql
      version: "15.5.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: guacamole
      interval: 12h
  values:
    global:
      defaultStorageClass: longhorn-crypto-per-volume
      postgresql:
        auth:
          existingSecret: guacamole
          secretKeys:
            adminPasswordKey: postgresPassword
            userPasswordKey: password
            replicationPasswordKey: replicationPassword
          database: guacamole
          username: guacamole
