
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hibiscus-server
  namespace: hibiscus-server
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hibiscus.lan.vandelocht.uk`)
      kind: Rule
      services:
        - name: hibiscus-server
          port: 8080
  tls:
    secretName: hibiscus-lan-vandelocht-uk-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hibiscus-lan-vandelocht-uk
  namespace: hibiscus-server
spec:
  secretName: hibiscus-lan-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "hibiscus.lan.vandelocht.uk"
  dnsNames:
  - "hibiscus.lan.vandelocht.uk"
