apiVersion: v1
kind: Namespace
metadata:
  name: ceph-csi-rbd
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ceph-csi
  namespace: flux-system
spec:
  interval: 5m
  url: https://ceph.github.io/csi-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
  namespace: ceph-csi-rbd
spec:
  interval: 5m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ceph-csi-rbd
      version: "3.14.0"
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
  values:
    csiConfig:
      - clusterID: "fdef4f57-7ea2-4931-ad44-b347bbcc8141" # From `ceph mon dump`
        monitors:
          - "192.168.178.40:6789" # Proxmox Ceph monitor IPs
          - "192.168.178.41:6789"
          - "192.168.178.42:6789"
    rbac:
      create: true
    storageClass:
      create: false
    secret:
      name: csi-rbd-secret
      create: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-rbd-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "fdef4f57-7ea2-4931-ad44-b347bbcc8141"
  pool: "kubernetes"
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-rbd
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-rbd
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-rbd
reclaimPolicy: Retain
allowVolumeExpansion: true
