---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2proxy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2proxy
  namespace: oauth2proxy
spec:
  interval: 5m0s
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2proxy
  namespace: oauth2proxy
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.12.11"
      sourceRef:
        kind: HelmRepository
        name: oauth2proxy
        namespace: oauth2proxy
      interval: 12h
  values:
    config:
      existingSecret: oauth2-secret
      configFile: |
        provider = "keycloak-oidc"
        oidc_issuer_url = "https://keycloak.vandelocht.uk/realms/k8s"
        email_domains = ["*"]
        upstreams = ["static://202"]
        redirect_url = "https://oauth2proxy.vandelocht.uk/oauth2/callback"
        scope = "openid email profile"
        pass_access_token = true
        pass_authorization_header = true
        pass_user_headers = true
        set_authorization_header = true
        cookie_domains = ".vandelocht.uk"
        cookie_name = "_oauth2_proxy"
        cookie_refresh = "2m"
        cookie_expire = "24h"
        code_challenge_method = "S256"
    extraArgs:
      provider-display-name: Keycloak
      skip-provider-button: true
      oidc-extra-audience: "oauth2proxy"
      reverse-proxy: true
