apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:6EwhYoxweZNUaXIyEFgssg==,iv:9tNlV8yo50boeb27tdJYsGlas8vRI2x2lkBKuYzQEtc=,tag:s3ctWndxhPFLltXCcIDG6g==,type:str]
    client-secret: ENC[AES256_GCM,data:bVD3LBvVul3EsEv7tIjPhaOXUei+yR/MBXVvJ2gqzQWKci+SK2tjOtjNVh0=,iv:ivJCWL5cP18gAx8OrKW+jeo9CWKUwJU2aKjiwCewdlE=,tag:OXkqxn5Zn/MZXcfMpqwRjQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:sJrso6hlmQHv6qtqccN6w7rrojTeaBBYLmVRHkwtFOOjvstvBog+4SUL9/HRccJpnoqTAjGmOjNmkTqb,iv:7YcWd8QfVv3mb7u3HNW2luc4WVrjv02tLzV6u1n8ROc=,tag:ywsaptXtsPiJ1jDM3QPb8Q==,type:str]
kind: Secret
metadata:
    name: oauth2-secret
    namespace: oauth2proxy
sops:
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWWw1ZTF3aVhWd2IxVGs1
            eURuQjRIU05jNlVmVkJqeGRnc0o4WERQYUJVCndrbkJDWXFldTZBdnEyaUo1b0Nq
            YVJLWGxOSEI4M011WnBLYjNCcm5nNm8KLS0tIHpXREJFSDBWb3hld0VEamUxR0t2
            ZTByS1hTZjNsNCt5QWJaMGlHUlJOdFkKMXHt2C18mZ5kJ0wPcshdX+CWILZ5yB2R
            SxS7vj3yfMXKpdFBYPQBENCqUSI0k/roLK9dhAgtQnYWCC0Be2RVIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T20:17:59Z"
    mac: ENC[AES256_GCM,data:218+HRxstIw8MSHkTpmfvoPkFuabU7FnjPgrrTRHp6DogqGShTSZO4u6aObXdWdHMtHvu5a/lXZiKYWEiGpN4xDgyo+eCg/Aji1yAppE9dv7pwBVNFYv6y3msu0kuQ1UmBnMbitTevoCmolY4EXGvZHE/gy+ton6U49CLt5Vcxk=,iv:CEiLtGxvs986sMG6H4w91pB7aLfwVaDmuJnRrDCEKUU=,tag:UDw0UwlPGm3/cbHivV7OAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
