apiVersion: v1
data:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:AfwT0Um1+oYD1XwkWVds0r5bFLIlr+6HPVenyLzW2DoZwuXi2HtnnvOlOi8=,iv:KJr6R27GEIQ93gAU4D9ji/bUY7TCDtGVRl9I+TtO1MA=,tag:XIamtwiGLqtgEWnYuNjZIQ==,type:str]
kind: Secret
metadata:
    name: grafana-client-secret
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNWFOd3V2S1VNNU5raFVp
            bzdXdStSMk5NQzhhdnRMQ3J5NE9qajU4Q24wCnhnbXpyQlBKMGIwRUdtNmZHSGlQ
            N0hkaVl4VWl4b1ZhWm1RSjFmWGJReTgKLS0tIEtiODhqbS9Nam9POVJUZ2V1dnFK
            TWR0cWIvYWJPRy9jZkdJUjJmQ1ZnZUkKPJgeOJ8BpeeuaiHljA1PP+pRbSk1xeME
            duKns42NSxjzDa4YieMxRSi1kxeyVy+Ex6+KwvSFoztWlkGzUlzLbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T11:21:58Z"
    mac: ENC[AES256_GCM,data:75ebDgvagMRpFExLL2k65wIxpLHVQzuFGEA5wheFckw+L/ZjoQ7fC/SVVgsmVSXfaC7N7A/DO7TQq+cFPbseaO6Or1cNUNX2E8D2WCZB1BUdUDvuj8xUICFsL+lEth8oCIfBTJjNFN7Xr/OitKGkftgSLY4Z539mCn2nKWFYBSI=,iv:NK8VMizaSRhn3Ky1YDvaWZdPjHxQCOu5LorvbCOap9c=,tag:Q7S339hRFfNxIvGj4F66hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
