apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "70.4.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    installCRDs: true
    alertmanager:
      enabled: true
      alertmanagerSpec:
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
              # storageClassName: "longhorn-crypto-per-volume" # Optional
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
        storageSpec:
          volumeClaimTemplate:
            spec:
              # storageClassName: "longhorn-crypto-per-volume"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 15Gi
    grafana:
      grafana.ini:
        dashboards:
          default_home_dashboard_path: /tmp/dashboards/kube-overview.json
      defaultDashboardsEnabled: false
      admin:
        existingSecret: "grafana-secret"
        userKey: admin-user
        passwordKey: admin-password
      additionalDataSources:
        - name: InfluxDB
          type: influxdb
          url: http://192.168.178.153:80
          access: proxy
          isDefault: false
          jsonData:
            version: Flux
            organization: HomeLab
            defaultBucket: Proxmox
          secureJsonData:
            token: ${INFLUXDB_TOKEN}

      envFromSecret: influxdb-grafana-secret
      # persistence:
      #   enabled: true
      #   # storageClassName: "longhorn-crypto-per-volume"
      #   size: 1Gi
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: prometheus-pushgateway
# spec:
#   timeout: 15m
#   interval: 30m
#   install:
#     crds: Create
#     remediation:
#       retries: 3
#   upgrade:
#     crds: CreateReplace
#     remediation:
#       retries: 3
#   chart:
#     spec:
#       chart: prometheus-pushgateway
#       version: "2.15.0"
#       sourceRef:
#         kind: HelmRepository
#         name: prometheus-community
#         namespace: monitoring
#       interval: 12h
#   values:
#     service:
#       type: LoadBalancer
#       port: 9091
#       targetPort: 9091
#       portName: http
#     serviceMonitor:
#       enabled: true
#     persistentVolume:
#       enabled: true
#       size: 2Gi
