---
apiVersion: v1
kind: Namespace
metadata:
  name: matrix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: matrix
  namespace: matrix
spec:
  interval: 5m0s
  url: https://small-hack.github.io/matrix-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix
  namespace: matrix
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: matrix
      version: "20.0.0"
      sourceRef:
        kind: HelmRepository
        name: matrix
        namespace: matrix
      interval: 12h
  values:
    matrix:
      serverName: "vandelocht.uk"
      hostname: "matrix.vandelocht.uk"
      adminEmail: "jan@vandelocht.uk"
      federation:
        enabled: true
      registration:
        enabled: false
        existingSecret: "matrix-shared-secret"
        secretKey: "registrationSharedSecret"
      serve_server_wellknown: true

    s3:
      # Enable S3 storage via synapse-s3-storage-provider
      enabled: true
      endpoint: "http://192.168.178.58:9000"
      bucket: "matrix-media"
      existingSecret: "matrix-minio"
      secretKeys:
        accessKey: "S3_ACCESS_KEY"
        secretKey: "S3_SECRET_KEY"
      cronjob:
        enabled: true
        schedule: "0 0 * * *"
        file_age: 2m

    postgresql:
      enabled: false
    externalDatabase:
      enabled: true
      existingSecret: matrix-cnpg
      # if externalDatabase.existingSecret is provided, the following are ignored
      # password, username, hostname, database
      # secretKeys to grab from existingSecret

    element:
      enabled: false
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-postgres-cluster
  namespace: matrix
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: matrix
      owner: matrix
      secret:
        name: matrix-cnpg

  storage:
    size: 15Gi
  monitoring:
    enablePodMonitor: true
