apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mautrix-whatsapp
  namespace: matrix
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: matrix
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mautrix-whatsapp:
        type: statefulset
        containers:
          app:
            image:
              repository: dock.mau.dev/mautrix/whatsapp
              tag: v0.12.3
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /_matrix/mau/live
                    port: 29318
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /_matrix/mau/ready
                    port: 29318
    service:
      app:
        controller: mautrix-whatsapp
        publishNotReadyAddresses: true
        ports:
          http:
            port: 29318
    persistence:
      config:
        type: secret
        name: mautrix-whatsapp-config
        globalMounts:
          - path: /data/config.yaml
            subPath: config.yaml
            readOnly: true
      registration:
        type: secret
        name: mautrix-whatsapp-registration
        globalMounts:
          - path: /data/registration.yaml
            subPath: registration.yaml
            readOnly: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mautrix-whatsapp-postgres-cluster
  namespace: matrix
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: whatsapp
      owner: whatsapp
      secret:
        name: mautrix-whatsapp-cnpg

  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
