apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mautrix-whatsapp
  namespace: matrix
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: matrix
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mautrix-whatsapp:
        containers:
          app:
            image:
              repository: dock.mau.dev/mautrix/whatsapp
              tag: v0.12.3
    service:
      app:
        controller: mautrix-whatsapp
        ports:
          http:
            port: 29318
