apiVersion: v1
kind: Secret
metadata:
    name: mautrix-signal-registration
    namespace: matrix
type: Opaque
stringData:
    registration-signal.yaml: ENC[AES256_GCM,data:qs1SB+OU+h48d8HVBZSdubRRx6NX6aNb3SlJtV8LpSwI94kNN1JXJxkhcDigd2ZNC6lvuh7s6aEE801kfIC3LdjNnLs+vDcLKlsBSRokGIZFqq27mLrAFI2jl5V68oArY/M0lPe+zsAWxAU4RismvLhBqeg+MbM6qsheapTxQv8ge6srCdGBcag0yMdjloOUeqLQ/AYC51cRWWWlE6uCMDGWf018mzu/PFafkQ1BW8/nJj+c6lDObCKcyJwhfMemQVKsO9J+h+2vXxDRYQzAVX21OBupyxJBg0CtLiTDBtyiWPBo/3ILCLeCYqMerKH8tmuOIb6OoVZ09uwpmOPDZxJ6fNeVbQZGHYIOegiObCI6a0G70yK10qb7G0OjwemraEgCzIac66BLeqXSLw08ii02VpDtTULD/y+h8qXHU1fFWYLXgdLR0Cjou/11pqAJahMBDhhJOwOJ7AEkZt97IhFtawY98Qq56GmIhpuACkqgoROOD0lp6obiJ4fKRbZZ33H8UZNcmjmMj0i93klgkef0gRNvXEO/VN6w0c/rT2XXZCnLewL7B2eZFW3up5KfeT8wJIO+yYWc5HzIsnUhJOAQ85aP7ia0ZFAfJIJXgwuaZdY40z14SPLONJEsj/tmbuvxI/NMo/gs,iv:DJrnuADb5TIQ2QAhC15URAVp/tdzmQyC9eIpoQ43jus=,tag:J7GhoH1gA9xDXu0gRtfyDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUFl0cG9RMndOM3dGOVR1
            Y3lRLzZoU0Z1dGNQWHZ1ekQ1ZmxwcWxSMFJ3CmxLMDNnMFgrNytnZC9jNklEMXdF
            SEcydVM0ampkZThZNC9qaWJCcGRQbUUKLS0tIEtRVCtVbFN2UGhMaHRzNFBjVWJv
            U09rTUJrbFhRTGtyV09XNzhDVnBCRmcKXqqMnoafuQg2ZQwcnCfo3BDjkXq9SkFq
            H2O9q3tc6qMlO8kQv3Ugr46+EljeWDjWo+T+qz2a1oBPCF7DasNf6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T05:07:17Z"
    mac: ENC[AES256_GCM,data:i5AYosx+ZTxdaxAKk+QR1hHVMjl5nDKk6QSbil6Mzidw2hl+sq9LjPuNfB0ZFL666c7GlK5mE/ew3BY2zTZdz2EQHiYGRZKcsmnrXsSGPrUtAyuES7P67aeSMfF4KvGkYyAwDO56DccnaBKY7tni72BwaWhuGzWz9BVc/ZgHmuE=,iv:EjasMfWHsmxCOtftf1u6cylBMbNcKR3ZWVvuEdXeetA=,tag:v2SPa1UYIK9bnEkjJkggKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
