apiVersion: v1
kind: Secret
metadata:
    name: mautrix-signal-registration
    namespace: matrix
type: Opaque
stringData:
    registration-signal.yaml: ENC[AES256_GCM,data:EqnzScaR/nmZtWh2wp0xhrfrj3QkrdhOgeE8WksyDY8uEI34/P7kwTsza6NzDIoiyvWvsLHHDGQYiSEzGcVED0oOjPfq7FkdDIcg19Pcw7GBi72ixPwtEhhKdvqWe54Fs60Wiw4ybyXLcIyrx52fQfymZJtcjMyPmGl9GneNvwsjT7sajlLnzD/IO5nGRhGqzYyS8ru921AmClgCqyAuxog//IeouRljGklbpWzwJS0DOyzNwpVbhFMe09hdteCW3XTBMQpq7vvtd867SxyfIQZeg3X6YyyclWqe1FIijMhk2dYgPVQNFQ3jwCdfUN+nktAv7aWS7FRdfz5rqs88O7bMSvoioi+GaXyfRO0R4NLq2TRdKPz0xr0gH5eveB6IVOP2/PxyZzbDhuVADIPCVkBjPk/xDFJIZp+7PUs75u+AV5dJ33XgB8RsD9delKEufmLOzRTTXmluk7qCV5eAaHr4s5b8W4LNRk/DpNPWg1rvOsOYujLm/GaHCE/U4vySoZm+kXq7UvF9AV8/MHuN5dsr7y8AQDB7H1vj8p1Ay5TEvJL1aKlV9gYUCAmYwRT4OwtnOXtEDEL2oe3tJJDonCe+4WHqbn0RB73iarCntcYipC+HtSYu2y8XjE11,iv:Hs9c1Mnu754cPq98oSR51IMsMl23v+GiCfoY6deofwU=,tag:HuVnIUrj6sIGKRT0P40TIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWkVnNjR4VER0aGU3akEx
            RkZrOThJOVBGQmhnT01seXBrdFdiWWlNRGljClNBMHhOTXlvQ0t2amRGc05nMEkz
            cmluSWtiZlluejRjYVFWV0hnZXhIZ2MKLS0tIFBGR3ljZWsyV1k0d2ZvYlF0akRJ
            UFdhNWNFcnlMaUwyVmVTWEVNVEhqYkEKwlvOoaxqTMZsQaKFg+3RjmClvtpcutge
            NDhfFgSTj2nraQE3t9GZKRm1r13Rt5K68GgE17ZmdYJAW4U86ThAoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T05:41:13Z"
    mac: ENC[AES256_GCM,data:Bxx62mfY/R7Scfh30upQid9DgUNQ0iL/FGvIvMPUnV/d+XGmSDTqnZFbFaGHYH0qNk68AQY7H8+OoH9eb3P7HE3Bid+SDjwKZp6NUn8BeAgL0SxBzXOd7moLvXZBKZddvDgEda3+xPT6N6dxnlwgsSAdurYdTx6XthrIwDdQiU4=,iv:M5Fwl0FJxrhUzkU1pGuo1bI+jOoNyCPK1CcZAiwE3D8=,tag:+SjuiqbDvczQjp9GHoPsLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
