---
apiVersion: v1
kind: Namespace
metadata:
  name: matrix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synapse
  namespace: matrix
spec:
  interval: 5m0s
  url: https://ananace.gitlab.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix
  namespace: matrix
spec:
  timeout: 20m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: matrix-synapse
      version: "3.12.7"
      sourceRef:
        kind: HelmRepository
        name: synapse
        namespace: matrix
      interval: 12h
  values:
    image:
      repository: ghcr.io/dotwee/matrix-synapse-s3
      tag: v1.137.0
    serverName: vandelocht.uk
    publicServerName: matrix.vandelocht.uk
    signingkey:
      job:
        enabled: false
      ## Specify an existing signing key secret, will need to be created in advance.
      existingSecret: matrix-signingkey
      existingSecretKey: signing.key
    wellknown:
      enabled: true
    postgresql:
      enabled: false
    externalPostgresql:
      host: matrix-postgres-cluster-rw
      port: 5432
      username: matrix
      existingSecret: matrix-cnpg
      existingSecretPasswordKey: password
    redis:
      enabled: true
      auth:
        enabled: true
        ## Or use existing secret with "redis-password" key
        ## instead of static password
        existingSecret: matrix-redis
    ingress:
      traefikPaths: true
      tls:
        - secretName: matrix-vandelocht-uk-production-tls
          hosts:
            - vandelocht.uk
            - matrix.vandelocht.uk
    persistence:
      enabled: true
      existingClaim: synapse-media-storage
    extraConfig:
      app_service_config_files:
        - /synapse/config/conf.d/registration.yaml
        - /synapse/config/conf.d/registration-signal.yaml
    synapse:
      extraVolumes:
        - name: mautrix-whatsapp-registration
          secret:
            secretName: mautrix-whatsapp-registration
        - name: mautrix-signal-registration
          secret:
            secretName: mautrix-signal-registration
      extraVolumeMounts:
        - name: mautrix-whatsapp-registration
          mountPath: /synapse/config/conf.d/registration.yaml
          subPath: registration.yaml
          readOnly: true
        - name: mautrix-signal-registration
          mountPath: /synapse/config/conf.d/registration-signal.yaml
          subPath: registration-signal.yaml
          readOnly: true
  valuesFrom:
    - kind: Secret
      name: values-matrix-secret
      valuesKey: values.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-media-storage
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-postgres-cluster
  namespace: matrix
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: synapse
      owner: matrix
      secret:
        name: matrix-cnpg

  storage:
    size: 25Gi
  monitoring:
    enablePodMonitor: true
