apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: matrix
spec:
  interval: 5m0s
  url: https://bjw-s-labs.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse-admin
  namespace: matrix
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: matrix
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      synapse-admin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/etkecc/synapse-admin
              tag: v0.11.1-etke45
    service:
      app:
        controller: synapse-admin
        ports:
          http:
            port: 80

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: admin.vandelocht.uk
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: admin-vandelocht-uk-production-tls
            hosts:
              - admin.vandelocht.uk

    # Optional: Persistence for logs or custom config
    persistence:
      config:
        enabled: true
        type: configMap
        name: synapse-admin-config
        globalMounts:
          - path: /app/config.json
            subPath: config.json
            readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-admin-config
  namespace: matrix
data:
  config.json: |
    {
      "restrictBaseUrl": [
        "https://matrix.vandelocht.uk"
      ],
    }
