---
apiVersion: v1
kind: Namespace
metadata:
  name: matrix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synapse
  namespace: matrix
spec:
  interval: 5m0s
  url: https://ananace.gitlab.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix
  namespace: matrix
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: matrix-synapse
      version: "3.12.5"
      sourceRef:
        kind: HelmRepository
        name: synapse
        namespace: matrix
      interval: 12h
  values:
    image:
      repository: ghcr.io/dotwee/matrix-synapse-s3
      tag: v1.136.0
    serverName: vandelocht.uk
    publicServerName: matrix.vandelocht.uk
    wellknown:
      enabled: true
    postgresql:
      enabled: false
    externalPostgresql:
      host: matrix-postgres-cluster-rw
      port: 5432
      username: matrix
      existingSecret: matrix-cnpg
      existingSecretPasswordKey: password
    redis:
      enabled: true
      auth:
        enabled: true
        ## Or use existing secret with "redis-password" key
        ## instead of static password
        existingSecret: matrix-redis
    ingress:
      traefikPaths: true
      tls:
        - secretName: matrix-vandelocht-uk-production-tls
          hosts:
            - vandelocht.uk
            - matrix.vandelocht.uk
    extraConfig:
      app_service_config_files:
        - /synapse/config/conf.d/registration.yaml
      media_storage_providers:
        - module: s3_storage_provider.S3StorageProviderBackend
          store_local: true
          store_remote: true
          store_synchronous: true
          config:
            bucket: matrix-media
            endpoint_url: http://192.168.178.58:9000
            access_key_id: "${S3_ACCESS_KEY}"
            secret_access_key: "${S3_SECRET_KEY}"
    synapse:
      strategy:
        type: Recreate
      extraEnv:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: matrix-minio
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: matrix-minio
              key: S3_SECRET_KEY
      extraVolumes:
        - name: mautrix-whatsapp-registration
          secret:
            secretName: mautrix-whatsapp-registration
      extraVolumeMounts:
        - name: mautrix-whatsapp-registration
          mountPath: /synapse/config/conf.d/registration.yaml
          subPath: registration.yaml
          readOnly: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-postgres-cluster
  namespace: matrix
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: synapse
      owner: matrix
      secret:
        name: matrix-cnpg

  storage:
    size: 15Gi
  monitoring:
    enablePodMonitor: true
