apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-prometheus-stack
  - ingressConfig.yaml
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
