---
apiVersion: v1
kind: Namespace
metadata:
  name: ntfy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: wrenix
  namespace: ntfy
spec:
  interval: 5m0s
  type: "oci"
  url: oci://codeberg.org/wrenix/helm-charts/ntfy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: ntfy
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ntfy
      version: "0.5.4"
      sourceRef:
        kind: HelmRepository
        name: wrenix
        namespace: ntfy
      interval: 12h
  values:
    ntfy:
      baseURL: "https://ntfy.vandelocht.uk"
    persistence:
      enabled: true
