---
apiVersion: v1
kind: Namespace
metadata:
  name: unbound
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: unbound
  namespace: unbound
spec:
  interval: 5m0s
  url: https://pixelfederation.github.io/unbound
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unbound
  namespace: unbound
spec:
  timeout: 15m
  interval: 30m
  chart:
    spec:
      chart: unbound
      sourceRef:
        kind: HelmRepository
        name: unbound
        namespace: unbound
      interval: 12h
  values:
    containers:
      unbound:
        config:
          allowedIpRanges:
          - "0.0.0.0/0"
          localRecords:
          - name: "proxmox.lan.vandelocht.uk"
            ip: "192.168.178.40"
    service:
      type: LoadBalancer
      # loadBalancerIP: 192.168.178.152
      annotations:
        metallb.universe.tf/address-pool: unbound
      #
      # forwardZones:
      # - name: "fake.net"
      #   forwardHosts:
      #   - "fake1.host.net"
      #   forwardIps:
      #   - "10.10.10.10"


