---
apiVersion: v1
kind: Namespace
metadata:
  name: unbound
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: unbound
  namespace: unbound
spec:
  interval: 5m0s
  url: https://pixelfederation.github.io/unbound
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unbound
  namespace: unbound
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: unbound
      sourceRef:
        kind: HelmRepository
        name: unbound
        namespace: unbound
      interval: 12h
  values:
    metrics:
      enabled: true
    containers:
      unbound:
        config:
          allowedIpRanges:
          - "0.0.0.0/0"
          localRecords:
          - name: "nashorn.lan.vandelocht.uk"
            ip: "192.168.178.40"
          - name: "traefik.lan.vandelocht.uk"
            ip: "192.168.178.151"
          - name: "longhorn.lan.vandelocht.uk"
            ip: "192.168.178.151"
          - name: "grafana.lan.vandelocht.uk"
            ip: "192.168.178.151"
          - name: "actual.lan.vandelocht.uk"
            ip: "192.168.178.151"
          - name: "hibiscus.lan.vandelocht.uk"
            ip: "192.168.178.151"
          - name: "hibiscusql.lan.vandelocht.uk"
            ip: "192.168.178.155"
      healthz:
        image:
          repository: bopjiang/google_containers_exechealthz
          tag: "1.0"
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 2m
            memory: 10Mi
    service:
      type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: unbound
    meta.helm.sh/release-namespace: unbound
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/instance: unbound
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unbound
    helm.toolkit.fluxcd.io/name: unbound
    helm.toolkit.fluxcd.io/namespace: unbound
  name: unbound
  namespace: unbound
spec:
  endpoints:
  - path: /metrics
    targetPort: metrics
  namespaceSelector:
    matchNames:
    - unbound
  selector:
    matchLabels:
      app.kubernetes.io/instance: unbound
      app.kubernetes.io/name: unbound
