---
apiVersion: v1
kind: Namespace
metadata:
  name: unbound
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: unbound
  namespace: unbound
spec:
  interval: 5m0s
  url: https://pixelfederation.github.io/unbound
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unbound
  namespace: unbound
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: unbound
      sourceRef:
        kind: HelmRepository
        name: unbound
        namespace: unbound
      interval: 12h
  values:
    containers:
      unbound:
        config:
          allowedIpRanges:
          - "0.0.0.0/0"
          localRecords:
          - name: "proxmox.lan.vandelocht.uk"
            ip: "192.168.178.40"
          - name: "traefik.lan.vandelocht.uk"
            ip: "192.168.178.151"
          - name: "longhorn.lan.vandelocht.uk"
            ip: "192.168.178.151"
          - name: "grafana.lan.vandelocht.uk"
            ip: "192.168.178.151"
    service:
      type: LoadBalancer


