apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actual-server
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: traefik
    - name: cert-manager-config
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/actual
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: traefik
    - name: cert-manager-config
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/gitea
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hibiscus-server
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: traefik
    - name: cert-manager-config
    - name: metallb
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/hibiscus-server
  prune: true
  wait: true
