# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: actual-server
#   namespace: flux-system
# spec:
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
#   dependsOn:
    # - name: longhorn-config
#     - name: traefik-config
#     - name: cert-manager-config
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./apps/production/actual
#   prune: true
#   wait: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: gitea
#   namespace: flux-system
# spec:
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
#   dependsOn:
#     - name: longhorn-config
#     - name: traefik-config
#     - name: cert-manager-config
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./apps/production/gitea
#   prune: true
#   wait: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: hibiscus-server
#   namespace: flux-system
# spec:
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
#   dependsOn:
#     - name: longhorn-config
#     - name: traefik-config
#     - name: cert-manager-config
#     - name: metallb-config
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./apps/production/hibiscus-server
#   prune: true
#   wait: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: code-server
#   namespace: flux-system
# spec:
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
#   dependsOn:
#     - name: longhorn-config
#     - name: traefik-config
#     - name: cert-manager-config
#     - name: metallb-config
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./apps/production/code-server
#   prune: true
#   wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: guacamole
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: longhorn-config
    - name: traefik-config
    - name: cert-manager-config
    - name: metallb-config
    - name: cloudnative-pg
  interval: 1h
  retryInterval: 1m
  timeout: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/guacamole
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: longhorn-config
    - name: traefik-config
    - name: cert-manager-config
    - name: metallb-config
    - name: cloudnative-pg
  interval: 1h
  retryInterval: 1m
  timeout: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/forgejo
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: longhorn-config
    - name: traefik-config
    - name: cert-manager-config
  interval: 1h
  retryInterval: 1m
  timeout: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/homeassistant
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vernemq
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: longhorn-config
    - name: homeassistant
  interval: 1h
  retryInterval: 1m
  timeout: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/homeassistant/vernemq
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: longhorn-config
    - name: vernemq
  interval: 1h
  retryInterval: 1m
  timeout: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/homeassistant/zigbee2mqtt
  prune: true
  wait: true
