---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
