---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mojo2600
  namespace: pihole
spec:
  interval: 5m0s
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 12h
  values:
    dnsmasq:
      customDnsEntries:
        - address=/nas/192.168.178.10

      customCnameEntries:
        - cname=foo.nas,nas

    persistentVolumeClaim:
      enabled: true
    admin:
      enabled: false
