---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-claim
  namespace: gitea
spec:
  storageClassName: "longhorn-crypto-per-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgresql-claim
  namespace: gitea
spec:
  storageClassName: "longhorn-crypto-per-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: gitea
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: gitea
      interval: 12h
  values:
    existingSecret: gitea-admin-secret
    existingSecretKey: password
    adminUsername: jan
    adminEmail: jan@vandelocht.uk
    extraEnvVars:
      - name: ROOT_URL
        value: "https://gitea.vandelocht.uk"
      - name: DISABLE_REGISTRATION
        value: true
      - name: SHOW_REGISTRATION_BUTTON
        value: false
      - name: REQUIRE_SIGNIN_VIEW
        value: true
    #   config:
    #     server:
    #       ROOT_URL: https://gitea.vandelocht.uk
    #     service:
    #       DISABLE_REGISTRATION: true
    #       SHOW_REGISTRATION_BUTTON: false
    #       REQUIRE_SIGNIN_VIEW: true
    #     database:
    #       DB_TYPE: postgres
    #     indexer:
    #       ISSUE_INDEXER_TYPE: bleve
    #       REPO_INDEXER_ENABLED: true
    persistence:
      enabled: true 
      existingClaim: gitea-claim
    service:
      type: clusterIP
    postgresql:
        enabled: true
        auth:
          username: bn_gitea
          database: bitnami_gitea
          existingSecret: gitea-postgresql
          existingSecretPasswordKey: postgres-password
