---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: gitea
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m0s
  url: https://dl.gitea.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: gitea
      version: "2.3.x"
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
      interval: 12h
  values:
    global:
      storageClass: "longhorn-crypto-per-volume" 
    redis-cluster:
      enabled: false
    redis:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    persistence:
      enabled: true
    gitea:
      admin:
        existingSecret: gitea-admin-secret
        existingSecretKey: password
        adminUsername: jan
        adminEmail: jan@vandelocht.uk
      config:
        server:
          ROOT_URL: https://gitea.vandelocht.uk
        service:
          DISABLE_REGISTRATION: true
          SHOW_REGISTRATION_BUTTON: false
          REQUIRE_SIGNIN_VIEW: true
        database:
          DB_TYPE: postgres
          HOST: postgresql
          NAME: gitea
          USER: gitea
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
    service:
      type: ClusterIP
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: gitea
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: postgresql
      version: "15.5.21"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: gitea
      interval: 12h
  values:
    global:
      defaultStorageClass: longhorn-crypto-per-volume
      postgresql:
        auth:
          existingSecret: gitea-postgresql
          secretKeys:
            adminPasswordKey: postgresPassword
            userPasswordKey: password
            replicationPasswordKey: replicationPassword
          database: gitea
          username: gitea
