---
apiVersion: v1
kind: Namespace
metadata:
  name: anything-llm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anything-llm
  namespace: anything-llm
spec:
  interval: 5m0s
  url: https://la-cc.github.io/anything-llm-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anything-llm
  namespace: anything-llm
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: anything-llm
      version: "1.1.2"
      sourceRef:
        kind: HelmRepository
        name: anything-llm
        namespace: anything-llm
      interval: 12h
  values:
    ingress:
      enabled: false
    persistence:
      enabled: true
      size: 10Gi
  valuesFrom:
    - kind: Secret
      name: values-anything-llm-secret
      valuesKey: values.yaml
