---
apiVersion: v1
kind: Namespace
metadata:
  name: filen-cli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filen-cli-deployment
  namespace: filen-cli
  labels:
    app: filen-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filen-cli
  template:
    metadata:
      labels:
        app: filen-cli
    spec:
      containers:
      - name: filen-cli
        env:
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: filen-cli-secret
                key: s3-access-key-id
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: filen-cli-secret
                key: s3-secret-access-key
          - name: W_USER
            valueFrom:
              secretKeyRef:
                name: filen-cli-secret
                key: w-user
          - name: W_PASSWORD
            valueFrom:
              secretKeyRef:
                name: filen-cli-secret
                key: w-password
        command: ["/bin/sh"]
        args: ["-c", "node filen s3 --s3-access-key-id $S3_ACCESS_KEY_ID --s3-secret-access-key $S3_SECRET_ACCESS_KEY --s3-port 8080 webdav --w-user $W_USER --w-password $W_PASSWORD --w-port 9090"]
        ports:
        - containerPort: 8080
        - containerPort: 9090
        volumeMounts:
          - mountPath: /root/.config/filen-cli/
            name: filen-cli-claim
          # resources: {}
      restartPolicy: Always
      volumes:
        - name: filen-cli-claim
          persistentVolumeClaim:
            claimName: filen-cli-claim
---
apiVersion: v1
kind: Service
metadata:
  name: filen-cli
  namespace: filen-cli
spec:
  type: LoadBalancer
  selector:
    app: filen-cli
  ports:
  - protocol: TCP
    name: s3
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: webdav
    port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filen-cli-claim
  namespace: filen-cli
spec:
  storageClassName: "longhorn-crypto-per-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
