---
apiVersion: v1
kind: Namespace
metadata:
  name: filen-cli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filen-cli-deployment
  namespace: filen-cli
  labels:
    app: filen-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filen-cli
  template:
    metadata:
      labels:
        app: filen-cli
    spec:
      containers:
      - name: filen-cli
        image: filen/cli:v0.0.24
        env:
          - name: EMAIL
            valueFrom:
              secretKeyRef:
                name: filen-cli-secret
                key: email
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: filen-cli-secret
                key: password
          - name: S3-ACCESS-KEY-ID
            valueFrom:
              secretKeyRef:
                name: filen-cli-secret
                key: s3-access-key-id
          - name: S3-SECRET-ACCESS-KEY
            valueFrom:
              secretKeyRef:
                name: filen-cli-secret
                key: s3-secret-access-key
        args: ["--email $(EMAIL)", "--password $(PASSWORD)", "s3", "--s3-access-key-id $(S3-ACCESS-KEY-ID)", "--s3-secret-access-key $(S3-SECRET-ACCESS-KEY)"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: filen-cli
  namespace: filen-cli
spec:
  selector:
    matchLabels:
      app: filen-cli
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

