apiVersion: v1
kind: Secret
metadata:
    name: guacamole-cnpg
    namespace: guacamole
stringData:
    username: ENC[AES256_GCM,data:RyzhZAQew2sK,iv:K3WcqQTF4h1T5avmqLuF/K0+G8yY8o/WzbIlOXC3CVM=,tag:mxdZmadRoOXjwgbErvulGw==,type:str]
    password: ENC[AES256_GCM,data:0CMHhT4Ifaoqtlr0O+0cnlwYLB3Xuah1B43h6I8WC6OGr33vM7b3McUyx8LC,iv:lfVaVNl2yRv3zWRsFWderFDtwxeu/JLhwdGVPsEMgz4=,tag:PJtBLQo42Q+T5GH+jwaD7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNUl5VGlqNExSUCt1cHV0
            a3loalJKbUdKNXd4OUUvL1FUb1g5dlN0Q25NCmRUQzdHM2ZIQTQ3cnZTUzBNRVNK
            TzdvYmVZczdYMi9OZ21LWWhXejlUakEKLS0tIEQ0dUkvNzV6VTNNUDV3aERKS0dx
            UGl3YW9VZFl0UEMwK0RGNGo1YWpZYXcKVEpJVYXTnHlY2NmeGOFbRo4BmhMi921h
            vKEIeWHben2O4rg4y6snGEGwPh/befRL1S9PqyvDYqdk+be12565Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T11:58:43Z"
    mac: ENC[AES256_GCM,data:vDicurqY9vHwT6FOep1mPd1/ubRW9/fseILe5+pr6MptUsCie8QTqlz+FaTI3C/CMFSHRotu76DFIEldK1s9mPx63eBAqpryGZvGSslzP/PYg+e3HlTgGilmSGx3Dd4ONvjn/rqEo7h8pZO3c4dCTEnTUS3TCMjqNUx9iOGl79Y=,iv:OF9OrZfP2P5Kue2n+Fqav//bhAFeHGpnaZMt237NAWk=,tag:TLK5tNzhoq827OK4qX2KIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
