apiVersion: v1
kind: Secret
metadata:
    name: guacamole
    namespace: guacamole
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: guacamole
        meta.helm.sh/release-namespace: guacamole
stringData:
    postgresPassword: ENC[AES256_GCM,data:48ee0TkPhuOqgL6SGroJpt9hYI8SsjCfAgS1bnndM6qXgJ9FQ8o12NIItNZT,iv:Nkluf2qbiSv0RANTdo8P5jiP63A2u/P7lFx/UkG03yI=,tag:SsjA0RA1ckh3RJA89k06Yw==,type:str]
    GUACD_HOSTNAME: ENC[AES256_GCM,data:wpvOoftOWNCOIsA9c2s4,iv:WwfK9IqiJuTgtKmS9WB39U6zQnKluO28EgY0xcR58iE=,tag:epQAXq7XPwPuQqrBVLTJoQ==,type:str]
    GUACD_PORT: ENC[AES256_GCM,data:n+IvIw==,iv:R3NbCOAQIniGi/0nrCPh2A2FmXUJJXsCyyoljzDhvqE=,tag:UghPX2VhWNnvQAZK/wPL2A==,type:str]
    POSTGRES_HOSTNAME: ENC[AES256_GCM,data:pE4h+IKc+K8oHg==,iv:C5+4rdhZ8hSWP4NW8kMcUiu2nq8ViiASgJIjUIcn3Ho=,tag:3FQT2oRATpmqd3M/wj0lNg==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:gVodpg==,iv:HGKa5ck12sT3KwGQHiLk8GPelA0sRNlxXDpqkzv0b5o=,tag:yHxOe6bfWFJ1RbnytoA77w==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:6MfbH+OHb/C6,iv:j6undlfYtvjfFFxPs+nSCV+7CN7dKEKLJ3v1BrqVPgk=,tag:+Jl3CMkAJr5SW54cIhN9yA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:BEc4QnO+EHuU,iv:KXyi0rVF7LY11dPiDcAlK5mSHfG+0IDgyspmBSEzbVw=,tag:arFfr4fVtY+S9Yo6UIDj1g==,type:str]
    WEBAPP_CONTEXT: ENC[AES256_GCM,data:7y0AAA==,iv:EO238gvHiiX6RDtm/2ZidcwzkwV4jBoNiHl3RkZ+z/8=,tag:t+4MGG6/q5iy0qBW6s0tRg==,type:str]
    TOTP_ENABLED: ENC[AES256_GCM,data:Ob1swQ==,iv:XfJJVIMEq5Nrk+pt9BSoGp6U1aYNSv412UnpXcWls8k=,tag:swrAwT2vJ8gug628tpGNTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ3l5cTVyMTRER3pvTysx
            dzVNbk1mMUVOaVNWWEIwOENLM0FtRDlNSzBrCnpYVWJYYWdzd20rMXNNc0lVY2Jt
            Rmo2Z3daeHhXRyt4S0MyNWdQcVhmbjgKLS0tIGhQc092S2JDMGlqdWUwSWJiZGpo
            Y2lXK3N2K1ZnV1BlUVVxTW5ON3FUWlUKUIzVQUtZaXqfP1QuIPFA7HqkqDhdCNNr
            PS9PkBiHw+LfhftRHz7jxGMAeqvnidWTkyXB8+ft+1EjU7fTHxQWJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T11:58:43Z"
    mac: ENC[AES256_GCM,data:At65BU2ZMPvODqXVmMe78F4AhTgX+6vXbqPi5xvzUUO6ELRlxvOYab2UH1xjRxI8n5iVqBanAOlzd7w3RcxYvOigA5VbL5RwKBd98fUb9udZ5L6/lNwL1GMJIHCQ0D9osYUPMHOOzB2II16NJTeDtmNrY5NblPlBg/Weg76yBCU=,iv:cxp5v0C5n2QY1qh7/+IPTZwdxZm7u6i+s0wRrYXHkz8=,tag:TRT00rZJ50XRmmhhNjbDUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
