apiVersion: v1
kind: Secret
metadata:
    name: guacamole
    namespace: guacamole
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: guacamole
        meta.helm.sh/release-namespace: guacamole
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:iOzkrG884Pi4oSS7aqJtEWEiNWLKkzxs3B9rIXX1xJv3Bpqum+Vrv5Pc34gt,iv:EHPdqHuxisUZg2oPR/TiAmqGXVmi2jk/eEesLyQw+48=,tag:TbZjp2rjS8r6yuPV64xnyQ==,type:str]
    GUACD_HOSTNAME: ENC[AES256_GCM,data:xlEXh+eYrZkitxsEw/4f,iv:OYqvcFrjLkiYH2ow/RPQrWY6QIhDKZIzsVtfRbyY64M=,tag:XM4ohxmrXkDhfSHNROY2IA==,type:str]
    GUACD_PORT: ENC[AES256_GCM,data:33XnnQ==,iv:viKgB0Ry4pm5kfTSJqzhIJUkblRNXotJMdivI1shSuM=,tag:4Ue9nzhyVKaaFmcppuFB6Q==,type:str]
    POSTGRES_HOSTNAME: ENC[AES256_GCM,data:md4JXla5NSAR0hD+oNGktci2knUlV7FCtabNleE=,iv:nu5fy/ur0xLcZJ+gVoXha5+1TyqfdbGQHFkGcAiAkSw=,tag:/PwKBfoC5BG3zAzywpFsOQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:tosF8A==,iv:NOdgShdZzIrxI8Z5ntxZPyNzVz43+fPuvJ5hNR9e0fw=,tag:91k3UxIF0hs5TzyG80DilA==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:fVNKZ+adbZr6,iv:1XTe+agZ46aAf2dZAFI3w+m0GQ6y0+CHk7NHX6KBkEQ=,tag:I66/PpdPsOhFVQPvQvNNNA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Btvs55OktxNb,iv:2rm+Tc9JnLNjdDIyfQ9gwWdilXpKAK4Q+XJ2nxDn9kI=,tag:1cHs/nO5fmVUlcw1e9OVyg==,type:str]
    WEBAPP_CONTEXT: ENC[AES256_GCM,data:NCTiHA==,iv:OLtV6QhgDyfVvte1HvCnZbS5AulyJRSWgRR851fazJE=,tag:DYZqUS+kt4f+8I0oxPSWyg==,type:str]
    TOTP_ENABLED: ENC[AES256_GCM,data:/W4Acw==,iv:bZw72yLRsHFJZ5CWDageNZ9+HubdrOoD5ogzeM4mV4Y=,tag:y9yEUaNf/ERhbKsbbxVtcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNW5yYncrWXJrUWhOUjlU
            bGtZa3ZaZE0wWmg1dHhtRmpYdUZncGI1RWhNCmhpa29PRS9HYlFsdlFDMjBnSzRa
            b1JjZmhoeURxVFdpQXRRYnVzbDNaencKLS0tIHZMcVpuVXVaSU10ZjVxU2J3OXRE
            OFpxSGVSQVVBSVp4bk0zQ0ZheUYyZWcKvTi0wvCoRQbaQAtmlRsXJUprC29412Ld
            wUxnmEIgpa8p+nOcZcbiv9+urRBqBS6IOw3H92pQ1+lyJ1f4EsuDFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T13:18:58Z"
    mac: ENC[AES256_GCM,data:+G9fu7OxDWeqt+3ONgg83uXpEpy1bHN2fdcWiV/wEQNkw66cZ0RVg31ObBmR5Qv83WLkuMSDStLsT70WJO9u0zIlQNDcRG0S3dV2FQ6+pRMDUzbO99BA/pHzoO75aLA6kY6D7H+iYg3Hw2Q4HeHVGiFHlfDx/gC6SHf1ZK5sScU=,iv:VQJabkErvB3I5Hc0xOxDg7SpAVMVCow2sQKf161WZ3M=,tag:VHzn0lc13YGd+o4JpyzXlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
