apiVersion: v1
kind: Secret
metadata:
    name: guacamole
    namespace: guacamole
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: guacamole
        meta.helm.sh/release-namespace: guacamole
stringData:
    postgresPassword: ENC[AES256_GCM,data:47TuWWkLu4hcB/uJiNqbbnV4M2gmDOLG0QuO4NA+iTx2ZHVc/4diK/59OnKv,iv:QtB3xbiaTzDPU6MzYMCOGkHynw0M/Cer9h0BsDISXiM=,tag:whO65qyzFAJbs8clyQqR8w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WCBPzqJEXiteNLMpmpi6VjnJcdFwHiO5c/7wq3uv6ftoi/eD,iv:qZuAqp9lmxoCO5avQv/PktzCDkoSAS47RNwQq8i7sm4=,tag:rbA9nBjqAUEwmA0P6UXGvw==,type:str]
    replicationPassword: ENC[AES256_GCM,data:d58mHcdLa/htDGJy0hpdHeXYe+fzpgH8NLbBEfvF8+JyAfENVxAk6DVOvRZe7KQ=,iv:WVCAV2FlRCYWXcNf6+nsmaZKvuYG+MyBpaTZMWRmCXE=,tag:mEaMtA1ZD+9DcTMj0bRqdA==,type:str]
    GUACD_HOSTNAME: ENC[AES256_GCM,data:l4InU6RgzP71WQpAY/yu,iv:hFP+7UlUoAfFgyt+vYLX3u8fO99NAZMQtlIHTw2doXU=,tag:0nZrzEYf2/HfOMG9cgXOQw==,type:str]
    GUACD_PORT: ENC[AES256_GCM,data:iS/+fw==,iv:o8Rn59cZddWYN0ERiglJ50he2mJDAu9Vif3u2lqnqbM=,tag:uc5cnyEasJQvEPLFD3cITA==,type:str]
    POSTGRES_HOSTNAME: ENC[AES256_GCM,data:zHVXCptmxYTyTg==,iv:9I+e5extjWs5H3xY0ISA777gl8Kj9ADFuxOCAo9/Mds=,tag:UMRXF1XD912vfciaQQkK7w==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:PZQv2Q==,iv:ErQwbyoFmr54Vx+CZZJt+BczNOTtBMXLnYTq+lVri5s=,tag:egTYAvETdWFglYaoonKX6Q==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:K4EXFdpF/2Ul,iv:sJrPe8qNb1D6rE0msnPXehIf0BEUXwPIY5WGQxUb1Bc=,tag:q9BmHdxte1g6vJLh7zNFww==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:pevH2zrrzE49,iv:JMuj8XOj11jpnKLoFr93voN6ki1FmqVk2umCBcSJY3I=,tag:4ee6lb+9bGr4J2l1LogcDQ==,type:str]
    WEBAPP_CONTEXT: ENC[AES256_GCM,data:ZjrQ2A==,iv:GGtqHlfZv20hehW/x+lfXFpTe6fxgjOpoeA1+uq3KC8=,tag:Cvd8jnxYi31jkqphh++o0g==,type:str]
    TOTP_ENABLED: ENC[AES256_GCM,data:mxb2Kw==,iv:0vOiyqRMzDzpOEYV7wKTLSvqfp5weQVgoIiNgmao5ZA=,tag:aErxCK5h6PRiz0UYyfX5Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ0YwZ1VRSDJ4QkNhY0E4
            OFVTdW1vTE92MC91bHVFQUNvODBkaU8xaTBBCkZtbC9uS3hIaXpsS2hCcVBrc00z
            M2JidWJOQzRUNEFDaU83ZE9XL1hqRG8KLS0tIDJobllVa1Zrbld0ckFEK0pqMWVL
            OVZ6OW1QK3lhQm05ZGVTS1hXL1BqZDgKNW5m/MOuM5RQBZJFxtDqm6lzAoP6L5tZ
            l1hXnzLvm1yfvGxIUo1MvDI4oRfatCPi2Ev2JuM0zCO7Y1PL5qhshw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T20:14:26Z"
    mac: ENC[AES256_GCM,data:pQIE5guA04m8CFIe6Si6PBaNBDaBgAAYVLIbFYneutzDxSttW6dDSLnWbaou/hb6UoG/RuypKmjH5L5VFZNh0dPYMlp7nST0+QmgezdJCS4kn992cGk//aeitJ5EUVeSVYEY5bYRAjhSVhlkBxR3KlKVR34GnRPH/RzuPCszBLQ=,iv:WFT+l0xwnWpUnA+xhl/teHq72vAEwJgA+yerAMlY7ag=,tag:gQ9wvTqUeA6QcRQgyuH4Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
