apiVersion: v1
kind: Secret
metadata:
    name: data-postgresql-0
    namespace: guacamole
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:WfWy1EyKcP1gMt0uPMDfB7ctRQyvT07tA1MjW9XHEfy7vceFrcuCIKLuARLwdW6p3uJ4vYo=,iv:gyef7n2qUZSYxRcts0CgND7UyqcguiQ5McTTAXa14PE=,tag:3wNYau6XvNFuZAPVtWOoEg==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:G85u10pk,iv:5QYvd5w3ntVCRlnhHsVQLM30WA18HLKOrGY174ccxWQ=,tag:RVxwKeAZOZxROISxWSej/g==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:RAWb6o8W++2cn4ICEh9E,iv:a6OjMVmvK+cBrGtsRPnXefRELws/cItSJAdBIpu0Hwg=,tag:YKZxprSPPnsnaSz7BAXSAA==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:sIEZw8MJ,iv:ea14FD/1FRkRmZ+T5NcJE23rqffnEWS95Urunr68Cao=,tag:RfZKQI9E8wm113o36B6LzA==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:gjAY,iv:O7LEhXXriKNtq0K91MdR1Vsyoj6nUoOxfzCBd/wpluk=,tag:4vSICS7G3wfINOIJFgp1fQ==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:P1lMG8PZJg==,iv:+uH66xmqhwAg2a7j/lb6Qb9kXFp7T5WMgOLZtVdq03w=,tag:ofhaMKObkA3rOJXR2Dmasg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVW8xZ0RGOXhKSFQzKzlw
            eHc4d2RZQ2ZXd2VJLzRwL3FueVVWRDdPS25FCktYVmxUb0k4cDk0clRtNm5VRGNR
            QTlqVllyNHRObHRpNldQYTZiSUxTUzQKLS0tIHZsR2wvOVhsMVk4RnJNaHM3V0c2
            ZkFIN3cyaGVTY2tFS0F0d09IWHRQWkkK/jUskPxaJZKrMD1vAjviywCXd9x+yJX1
            q/STKvq+GMAo6rouX0Mzj69tQ8SW7LLMT2CsoZqalJ2FMACj0Ke6sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-07T19:52:36Z"
    mac: ENC[AES256_GCM,data:SuYlChqrpjZIRcD+UbDjrtm3JykPmN92b+ry8Vcey3KyRGxHNqPfJdCY+uEidOVEihgzVbgatj+TCmR4briuBnUj+fTDNs0y7aPx+UIfhQnRTt/5qTj+LtVhRVdcgMso7yH8TevL3LcpVrnOt1qslz8JqBGW9NsKjQjtt9YTls8=,iv:LDmZq89ZKvGq639udaMomUsoacVZ1fWBhtowdaW+4wc=,tag:vuu6AJ8ztSFWpY5k/l5rYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
