apiVersion: v1
kind: Secret
metadata:
    name: guacamole
    namespace: guacamole
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: guacamole
        meta.helm.sh/release-namespace: guacamole
stringData:
    postgresPassword: ENC[AES256_GCM,data:L0Qjwp6rewEG3DIsRUIGmIz/cxkV11B9RhGKoWlS7ObXw8dQa3KWAhFHkiEl,iv:Fo+COW4Mxh2w4B9ZGzVIQv5SUyFQ+iQ1hr7D0apnrhc=,tag:axzu5pu4hEcUMWFZf/RDJA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:xhFB8dfDqYZ0wbmGL/0gf9RKMPi+muwL3vcvUFHSMa/v13Di,iv:AI4wnagup+8KczxTf8Y9+axTreb7LbmUqzb828QhWHE=,tag:rGT12XFw7Ul09KEa2l1pJA==,type:str]
    replicationPassword: ENC[AES256_GCM,data:sIRP47gzX5iUIbORX0LmQMHFyWhpnxrVQrGzEUSFDozOPh5yJSCZ0Ru7XS9SciM=,iv:SvPXzcI8YkrPHkPg02B6vKKTGCtBmpMrP8h2piFfTIU=,tag:GbD4u6tptyhbEdeHek+J7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaGRvdVNScERZZGpZZ0ZZ
            NUNLNmx1OG9sd2hFOUtoSmtoTGxKZUs5bkFJClphL05wYUpmclJQanp4cW1NNjNS
            M2haQ2JVMTNUdWhxeXBMMW1wL0FJRW8KLS0tIHhOM1ZwZ2ZQeFJSUVB0TXlXQXp2
            UG9PbjhiME5heWhzcktvbGFteGthVU0KJdobOpZhO5uSuDoSC4nj5FuJRVIFl0el
            uRqGJYH494UNeO43wG9IXrmM0f07dSqJmmSGsKlzQIlzW/++OZskag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-07T20:54:50Z"
    mac: ENC[AES256_GCM,data:pkZmoRcsTKGoruqkhwx7UjuRc6drAO857v1u60TFTEH102x29Vh6BSPmt32xg5mm0yXf3zMlSylQmKTICxe3IZtsErShUAUb5Z2UcJ+Nwdw/feuuCiR0/+sNr1TBtLNsffxUzObUeDVfhkif7XengfIsETM9iDEE4keY/zL30Vg=,iv:fCzCeoa/vKyMxnd8ukuv7kszFT57zUE0B+tpS5ov4P8=,tag:pMHh9jwsXRIGW5PT8wmh+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
