apiVersion: v1
kind: Secret
metadata:
    name: guacamole
    namespace: guacamole
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: guacamole
        meta.helm.sh/release-namespace: guacamole
stringData:
    postgresPassword: ENC[AES256_GCM,data:KNL1WkGpk4VrFFGQrBP+jMbA+ZdLd6b/8hqEp0T90TPQfE1zaiqPl3iDBFJ7,iv:4ERAljxton4+Sp7CfpqIJppXxK4/7VyeX90Tpn7pTTM=,tag:4471hhI5fhE9JRsGflDIQQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DanCsYZkwzIWGWIH77MlC5IKU3PDZdRuJ4sQ1PwfrONovMYh,iv:ri/eJGGWxZ/fKPUZTues3mN/ow/gO09VrjSgmiAuMZA=,tag:HkGZwhY5rTfQpQfuKvHWAA==,type:str]
    replicationPassword: ENC[AES256_GCM,data:KkURkPUFn2rYda4pv85Xq1dNUhT0+rWnuaofq4a2ldG/Bat3umB3Oj2/fMqYaaM=,iv:d3Fwuga5DxTNzctH7o2+r4YE6khCeJodoJF4+kYBJxE=,tag:o7aCKNy9BaSS4VlitMWvlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVC9pczd5Wk9waDNHeWpu
            cEhuVGRZaTZkQjltYVZBNjY3RWVZRDJtdkJvCjBqdkhTRC83RzlyTUQybG5sYzR5
            d1pRbWZWLzNneFpuQ0VuWUlJaXp2QkkKLS0tIHFkc2JxdjkxVnplTGlBbWRvMVha
            cEpnOFpjR1FOOTVMaWs0V2lJWHIya0UKWNMli0PPEn1QJCcCmJXn3DB6G7VcP0Uv
            EzzuBJr0e5O95iYwMqWupy2vZ7n/geOBxFBjpUubG8ZED8EmE9UA1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-07T19:52:36Z"
    mac: ENC[AES256_GCM,data:UgcRBlFHntw6mwerLpq5xmhyILeoc98tvvvqFhlqTfdlw2ehpTn0MoPRbxulVb1mbg0PsxocFoi0okZkaQK4s9dDOs9kGlqjmN0dFpkPDjF3JMEo3HcAhCHVmhjLng/DoPPHt3Jxc5BUGZ8N4e+c7J9OejjUOF447oEMjNzMgPM=,iv:gOsM7EjuC2htKeuVj7Mz5Nv++OpbEqSbvhnEh+TjjX0=,tag:rHD9yMUKVmsgn2zCsc5nUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
