apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/guacamole
  - ingressConfig.yaml
  - guacamole-postgresql-claim-secret.yaml
  - guacamole-postgresql.yaml
  - guacamole-secret.yaml

# patches:
#   - path: patch.yaml
#     target:
#       kind: HelmRelease
