apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik
  - ingressConfig.yaml
  - secret-traefik-dashboard.yaml
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
