apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/code-server
  - ingressConfig.yaml
  - code-server-claim-secret.yaml
  - code-server-auth-secret.yaml

# patches:
#   - path: patch.yaml
#     target:
#       kind: HelmRelease
