apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwebui
  namespace: openwebui
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ai.vandelocht.uk`)
      kind: Rule
      services:
        - name: open-webui
          port: 80
          serversTransport: openwebui-transport
      middlewares:
        - name: svc-openwebui-headers
        - name: openwebui-compress
  tls:
    secretName: ai-vandelocht-uk-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-vandelocht-uk
  namespace: openwebui
spec:
  secretName: ai-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "ai.vandelocht.uk"
  dnsNames:
    - "ai.vandelocht.uk"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: svc-openwebui-headers
  namespace: openwebui
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: openwebui-compress
  namespace: openwebui
spec:
  compress: {} # Enables default compression (e.g., gzip)
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: openwebui-transport
  namespace: openwebui
spec:
  # Default is 2. Increasing allows more idle connections to be kept per host,
  # reducing connection setup latency for subsequent requests.
  maxIdleConnsPerHost: 10
  forwardingTimeouts:
    # Time to wait for a connection to the backend to be established.
    # Default is 30s. A lower value can give quicker feedback if a pod is slow to accept connections.
    dialTimeout: "5s"
    # Time to wait for a server's response headers after fully writing the request.
    # Default is 0 (no timeout). Setting this can be useful if openwebui sometimes is slow to start responding.
    responseHeaderTimeout: "120s"
    # Maximum amount of time an idle (keep-alive) connection will remain idle before closing itself.
    # Default is 90s.
    idleConnTimeout: "180s"
