---
apiVersion: v1
kind: Namespace
metadata:
  name: authelia
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m0s
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: authelia
      interval: 12h
  values:
    configMap:
      session:
        cookies:
          - domain: "vandelocht.uk"
            subdomain: "auth"
      storage:
        local:
          enabled: true
      notifier: 
        filesystem:
          enabled: true
      authentication_backend: 
        file:
          enabled: true
