---
apiVersion: v1
kind: Namespace
metadata:
  name: authelia
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m0s
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: authelia
      interval: 12h
  values:
    resources:
      limits:
        cpu: 100m
        memory: 125Mi
      requests:
        cpu: 50m
        memory: 50Mi
    ingress:
      enabled: true
      tls:
        enabled: true
        secret: 'auth-vandelocht-uk-production-tls'
      traefikCRD:
        enabled: true
        entryPoints:
          - websecure
        disableTLSOptions: true
    pod:
      kind: Deployment
      replicas: 1
      extraVolumeMounts:
        - name: users-database-yml
          mountPath: /configUsers
          readOnly: true
        - name: smtp-secret
          mountPath: /smtp
          readOnly: true
      extraVolumes:
        - name: users-database-yml
          secret:
            secretName: users-database-yml
        - name: smtp-secret
          secret:
            secretName: smtp-secret
    configMap:
      session:
        cookies:
          - domain: "vandelocht.uk"
            subdomain: "auth"
      authentication_backend: 
        file:
          enabled: true
          path: /configUsers/users_database.yml
      access_control:
        rules:
          - domain: 'auth.vandelocht.uk'
            policy: 'two_factor'
          - domain: 'longhorn.lan.vandelocht.uk'
            policy: 'two_factor'
          - domain: 'traefik.lan.vandelocht.uk'
            policy: 'two_factor'
  valuesFrom:
    - kind: Secret
      name: values-authelia-secret
      valuesKey: values.yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-postgres-cluster
  namespace: authelia
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  bootstrap:
    initdb:
      database: authelia
      owner: authelia
      secret:
        name: authelia-cnpg

  storage:
    size: 1Gi
