configMap:
    notifier:
        smtp:
            enabled: ENC[AES256_GCM,data:TukAbg==,iv:4+HoCgzF14xl0knbe7MCULLjXeFxTwCfNhvOtVShVvc=,tag:T56S5JfD2jewTHigpaOnqw==,type:bool]
            address: ENC[AES256_GCM,data:w4hbjLWJXyqXkr/oun6/Y+Q3f17/1yUe1q8/Pdkz3epmLKgH,iv:8ioOgB8YV7Yvz6hVsky8sK5+/gYvNy1NuHnkuVYuKWk=,tag:c4+a6Qr1F9uome9d+Je3bg==,type:str]
            username: ENC[AES256_GCM,data:T/h8pYpgxXF6kUfWKVSsIjiGvg==,iv:JhBcdFvHhxhShlqoJMN4zMH/NTJg9db5YwODyMneztk=,tag:Yh4SJLNjuQkd3SBP5tqOcA==,type:str]
            sender: ENC[AES256_GCM,data:kIgLpnQtIzNoH+oxz2u4EkdXMA==,iv:GW1VxonFiKdfMsC2BQPYAgz2CVN2E1jd7CYW9JChPYw=,tag:xD5i7TV7bfJVk721FEsuoQ==,type:str]
            password:
                value: ENC[AES256_GCM,data:7+jYZxzWCKi1KI0EbPn1hxu2/E0=,iv:dNNPLvvDk2UI8VgthOrl/RNNogXUpgV8+WLCSXa5PeQ=,tag:Q+ZEXe9H3EGPNoJ0HWNXfw==,type:str]
    storage:
        postgres:
            enabled: ENC[AES256_GCM,data:OlPFNw==,iv:JLH1Y5p3RIlYnbd92CB+9+UXtCpOj+v/rPa9XzqQtro=,tag:l3WbCLqXRXswSURWYzFcmA==,type:bool]
            deploy: ENC[AES256_GCM,data:Lr/dYn8=,iv:uUVAHaFnuO6CWHDnUXsPhhug6MC1oe/Sk6L+97M5URc=,tag:WsvA6DsNghBa4qeYWMNcpw==,type:bool]
            address: ENC[AES256_GCM,data:GCVFK2EDLZXnfBF3m4ZA1cUySNbakR3AiulQ+Jyz6eRMe2lTja2AdWOAOajqh9lra3tj5xn0i174caDc+85bdkUG,iv:vI69b8g4dFwr7d/hoPNFvpjogwNZmxHw9dJeYzPmXlo=,tag:ALXNo72lqTpqaYAgVtG+cA==,type:str]
            timeout: ENC[AES256_GCM,data:1F2lHG5mLU5/,iv:tnf020YVzvst5FQ+txT9GTI6HXj+5FBfQgnG876b9cU=,tag:1HA2z7ooVvZ1ZrBhm49euQ==,type:str]
            database: ENC[AES256_GCM,data:U9gNo/DCnEY=,iv:HVDX0+9+Z5Mb/nOpwLRvGeAMs/yFhRT2Zux2tvuw1j8=,tag:hFxLRQshYiJi1VGRhijXng==,type:str]
            schema: ENC[AES256_GCM,data:UX+m5voT,iv:fGCN0UViL9IzgVKWZfhm2/q2AyIFpexXFPnydqrdck4=,tag:9W/dlkGpTRVF1abuGI9Duw==,type:str]
            username: ENC[AES256_GCM,data:WLt360eehe4=,iv:onZ716XoyJFy0/YYZbPranjt7fL0W7rEFugzMGAxmZg=,tag:pyCAfAhWZXK6tcWyCiTstw==,type:str]
            password:
                value: ENC[AES256_GCM,data:utOBr/m/+epx2iO7wbmicbFtA5OyA+crgCYUbjWYGixhNBvHZjp22d0M,iv:GRs5K/Nzajdk69cyEwsGPLc7lBRS8zf+V5cDFIVPvDk=,tag:vNoK33RxGGxpt6jjtPzkgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSG9DWStZWko3eEdQYi9i
            OWMxR0piODN0L1ljcnFBRHB5MTdXQVA1aERjCkcwYVJEZy8vNVFDYUNWS2pWUXZO
            TDVkVEJPZjZsVFgxTmZ5dWNKeDhCcUkKLS0tIGRPaC9DZFNPVjdrM1Y1Zi90SjNT
            SGh1b0poY0ZBY1Q2M2p6QWxrQlN1VDQK8fmN5op2n+TqtJ8+I9TcxkcsYxpUWUnj
            y78jn+XNUoYLFVu3j4K7KgVjEpRoc2Npqo0DOrvG0LUl8+h9PW36Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T08:13:14Z"
    mac: ENC[AES256_GCM,data:HCoxLbmvpGDAoBscZ71xBMRAAlAcDzbfwn1D39pELRnZv+19rJihm2Rt3TG5DrwRz466vGSrWRFoj7aLv+i1i2MqbwbpgynAJT2JPrEBTjMw91o9jBeu9vFCLkzr68TFY0em16LdW1FHOmtzjGbq9WDKVTZBB7ZW5UK7Ic4Y+Ow=,iv:mc5skI1DY+cvNaPNJOXGCW1vfey19hGdWqsokzibYfA=,tag:cY2uttQqH7hKwqgYzcIsRw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
