---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-lan-vandelocht-uk
  namespace: longhorn-system
spec:
  secretName: longhorn-lan-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "longhorn.lan.vandelocht.uk"
  dnsNames:
  - "longhorn.lan.vandelocht.uk"
