---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"

    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"

    deployment:
      enabled: true
      replicas: 3
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    ports:
      web:
        redirectTo:
          port: websecure
          priority: 10
      websecure:
        tls:
          enabled: true
          
    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false
      # file:
      #   # -- Create a file provider
      #   enabled: true
      #   # -- Allows Traefik to automatically watch for file changes
      #   watch: true
      #   # -- File content (YAML format, go template supported) (see https://doc.traefik.io/traefik/providers/file/)
      #   content: |
      #     # http routing section
      #     http:
      #       routers:
      #         homeassistant:
      #           rule: "Host(`james.vandelocht.uk`)"
      #           service: homeassistant
      #           entryPoints:
      #             - websecure
      #           tls:
      #             secretName: james-vandelocht-uk-production-tls
      #       services:
      #         homeassistant:
      #           loadBalancer:
      #             servers:
      #               - url: "http://192.168.178.44:8123"

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      # spec:
      #   loadBalancerIP: 192.168.178.151 # this should be an IP in the MetalLB range
      loadBalancerSourceRanges: []
      externalIPs: []
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: james-vandelocht-uk
  namespace: traefik
spec:
  secretName: james-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "james.vandelocht.uk"
  dnsNames:
  - "james.vandelocht.uk"
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: traefik
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123
---
kind: Endpoints
apiVersion: v1
metadata:
  name: home-assistant-service
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.178.44
    ports:
      - port: 8123
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingress
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`james.vandelocht.uk`)
      kind: Rule
      services:
        - name: home-assistant-service
          port: 8123
  tls:
    secretName: james-vandelocht-uk-production-tls


