# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: matrix
#   namespace: matrix
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`matrix.vandelocht.uk`)
#       kind: Rule
#       services:
#         - name: matrix-server
#           port: 2283
#       middlewares:
#         - name: svc-matrix-headers
#   tls:
#     secretName: matrix-vandelocht-uk-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matrix-vandelocht-uk
  namespace: matrix
spec:
  secretName: matrix-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "matrix.vandelocht.uk"
  dnsNames:
    - "matrix.vandelocht.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-vandelocht-uk
  namespace: matrix
spec:
  secretName: admin-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "admin.vandelocht.uk"
  dnsNames:
    - "admin.vandelocht.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-vandelocht-uk
  namespace: matrix
spec:
  secretName: chat-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "chat.vandelocht.uk"
  dnsNames:
    - "chat.vandelocht.uk"
