apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: filen-cli
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  dependsOn:
    - name: ceph-csi-rbd
  retryInterval: 5m
  timeout: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/filen-cli
  prune: true
  wait: true
