apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vernemq
  namespace: homeassistant
spec:
  interval: 5m0s
  url: https://vernemq.github.io/docker-vernemq
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: homeassistant
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: vernemq
      sourceRef:
        kind: HelmRepository
        name: vernemq
        namespace: homeassistant
      interval: 12h
  values:
    resources:
      limits:
        cpu: 100m
        memory: 270Mi
      requests:
        cpu: 100m
        memory: 270Mi
    persistentVolume:
      # Enable or disable persistence
      enabled: true
      # Access mode for the persistent volume claim
      accessMode: ReadWriteOnce
      # Size of the persistent volume claim
      size: 1Gi
