---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: authentik
      version: "2025.8.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 12h
  values:
    authentik:
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.io, and is fully opt-in
      error_reporting:
        enabled: false
      postgresql:
        host: authentik-postgres-cluster-rw
        name: authentik
        user: authentik
        port: 5432

    # server:
    #   ingress:
    #     ingressClassName: traefik
    #     enabled: true
    #     hosts:
    #       - authentik.vandelocht.uk
    #     annotations:
    #       cert-manager.io/cluster-issuer: letsencrypt-production
    #       kubernetes.io/ingress.class: traefik-external

    postgresql:
      enabled: false
    redis:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: values-authentik-secret
      valuesKey: values.yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres-cluster
  namespace: authentik
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-cnpg
  storage:
    size: 15Gi
  monitoring:
    enablePodMonitor: true
