apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.lan.vandelocht.uk`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: svc-longhorn-headers
        - name: forwardauth-authelia
          namespace: authelia
  tls:
    secretName: longhorn-lan-vandelocht-uk-production-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: svc-longhorn-headers
  namespace: longhorn-system
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-lan-vandelocht-uk
  namespace: longhorn-system
spec:
  secretName: longhorn-lan-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "longhorn.lan.vandelocht.uk"
  dnsNames:
  - "longhorn.lan.vandelocht.uk"
