apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/longhorn
  - ingressConfig.yaml
  - longhorn-r2-backups.yaml
  - longhorn-crypto-sc.yaml
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
