apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: endurain
  namespace: endurain
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`train.vandelocht.uk`)
      kind: Rule
      services:
        - name: endurain
          port: 8080
      middlewares:
        - name: svc-endurain-headers
  tls:
    secretName: endurain-train-vandelocht-uk-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: endurain-train-vandelocht-uk
  namespace: endurain
spec:
  secretName: endurain-train-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "train.vandelocht.uk"
  dnsNames:
    - "train.vandelocht.uk"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: svc-endurain-headers
  namespace: endurain
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
