---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: endurain-data-pvc
  namespace: endurain
  labels:
    app.kubernetes.io/name: endurain
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: endurain-logs-pvc
  namespace: endurain
  labels:
    app.kubernetes.io/name: endurain
    app.kubernetes.io/component: logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 2Gi