# This file contains encrypted Endurain application secrets
# Please replace the placeholder values with actual encrypted values using SOPS
# Run: sops --encrypt --age <age-public-key> endurain-secret.yaml > endurain-secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: endurain-secrets
    namespace: endurain
    labels:
        app.kubernetes.io/name: endurain
        app.kubernetes.io/part-of: endurain-platform
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lPL+ok4u2Qxh0UmVIzH2T3JrLp2V+/AyOUqXsLksS3NSPuZ3IizS1XmY,iv:QQS09NlNRUVfgq1fsYLMCThexP3oY7Huiifx6cN8axg=,tag:KmUZ4k8x5369HvWlEiJRUA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:chwSK8oyd9f9EgvLeHKQqgWqPJO2CQXnBIM4sULFMiQUyNVtjVUa1w6NnO5h5BVsP4i+5NjDEF/GVCEcifL7Fg==,iv:Id5Il2/XKolvsCMQucMqVLlKUvZJ5uVCy/e8Jsdjru4=,tag:rQ8Ub2o0flovgXMtUez9PQ==,type:str]
    FERNET_KEY: ENC[AES256_GCM,data:a/9/7dsC0krWyf5jT58Wzk9NWE2qabRAc7/wpPui/koXbt+bsoPipn4O4pQ=,iv:BBoqlwRy6DjJqdGpMBknI4zl6p+DwSkfcB/sx5sdekA=,tag:sNt5fPEU+K4pigQadNKfLA==,type:str]
    GEOCODES_MAPS_API: ENC[AES256_GCM,data:dUHr/gxBCIt7NTLpTEvsQ0UVLMi5hiTstNmrjQdhwQ==,iv:SLZIWhgWL64CyEnZaP+XL1qqf8IKMcEkS7r2fT65Eqg=,tag:j73mZRft0EOLml0/p/GlzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWUF5MlNwRi9HTy9Wb3Vv
            SEtTajVEQTFHRDdiV2ZKQVZYME9mT0h1UUVvClBEb1ZONndRaUVvZll6TFhmTlky
            NUlxZ2JUeWpiTzcvRk50ek9JclN3WlEKLS0tIEhZanVpSENqME9qNENQckpKVlJG
            M1NjWlBDb1Q5SmRRVmhMaFpGUFFVSDAKGOgrWF7MG2EFQSm2ULGstpq0TapkejSo
            FzIQOhEUC/Hi4TAX+MAQd6r4qLigKDgLIXeS927LNv75rpYz9d/uEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T18:55:28Z"
    mac: ENC[AES256_GCM,data:EclrgQkLoZidU6G6t1MDvA92klZ+8c6iZTGNLfRoJ+oLbOQai04enb5uX8kCKBXV6NIGy/I5Dj81uICcvBkddkWnBFrKniFFD5HklK6ouBidXUgDLEdHXhMbpnhuAKfpQFdtYIbbEbsCAyeYlURpDz3z+eCGWnqZs4QkJx5PwXQ=,iv:DIIbAGLfPvL7I4OsZFRGnc8crYYQx1BiZIHfySP4m4M=,tag:iRRhfbwcXVuvAUZDaZcj7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
