---
apiVersion: v1
kind: ConfigMap
metadata:
  name: endurain-config
  namespace: endurain
  labels:
    app.kubernetes.io/name: endurain
    app.kubernetes.io/component: config
data:
  TZ: "Europe/Amsterdam"
  ENDURAIN_HOST: "https://train.vandelocht.uk"
  BEHIND_PROXY: "true"
  POSTGRES_DB: "endurain"
  POSTGRES_USER: "endurain"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_HOST: "postgresql-rw.endurain.svc.cluster.local"
  POSTGRES_PORT: "5432"