# This file contains encrypted Endurain application secrets
# Please replace the placeholder values with actual encrypted values using SOPS
# Run: sops --encrypt --age <age-public-key> endurain-secret.yaml > endurain-secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: endurain-secrets
    namespace: endurain
    labels:
        app.kubernetes.io/name: endurain
        app.kubernetes.io/part-of: endurain-platform
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:HvATcMHDVUkoeur+HIjLWZPpdollZw0OqbXxNfLZQ9uSIx72DLm8WOUP,iv:tn1bzPDEi+y4ggwvuhUogAv1yaXFkeh+48NcoR4vog8=,tag:i3M7OAwXQPkrCCG89bpcTQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:lKm3D5RZaCNWvHl0574UjZjti8SDQILTFgm0N/kFRxo8O7a9GKCrQig8SXYDevpVJ+crwwy0/8EHJ0UvbpK35Q==,iv:7uZnyOFxuET5gNpORCsLn05Z4gKwOKnIVoJidPUh5kM=,tag:aBqR4GlgPTRfsRQ5x7TnGQ==,type:str]
    FERNET_KEY: ENC[AES256_GCM,data:gaZ4tVJKHUEKVJMcxZTyTKryUs6/P4DYstZGB2n2JOV+P4iWrI56QyUEzJY=,iv:BglBSi4E68uNScz0dwj0UH7BPdB9eEOCJrKQxJcrwu0=,tag:QUwKi1pnKC9AXWOrUavQ8g==,type:str]
    GEOCODES_MAPS_API: ENC[AES256_GCM,data:w6RLbu6vMII4YwxTgNK7XEbL13n1dfXUIMOLwfvq0Q==,iv:Ti8PLL6uUnBICS1yqso/1MoS1PM8Sg0nein9mS242Ak=,tag:oSssDg9XiGCShLR4aqh9aQ==,type:str]
sops:
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmhKalFXUUhNcUs2UWpl
            bGYwbkpNdkNUd1dJeDBtbTZBTkxLbm1PWjJrClRZUk5MVzhmS0F2NHZ5YnlLWlBt
            ZjcybUpDOThIajFQdTE4R0tFUVpHakkKLS0tIGVUc0c4Mk1WUStkUitpSGVIY0pD
            a2NOY2poVTQyN1FuNURubmtZV1BjOFkKsmTwEO7L+9QkI7Ed7A/5xqg4mdvrSSUh
            0xXpcWZxtAnFydjHElhBJtJhOQ/v3Lz9fSwYb5OK/xGkW5YpJWejZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T19:28:03Z"
    mac: ENC[AES256_GCM,data:IhnLmd3jnHh41Ejv/JOQ4CyRxaiI+UaTP1MXmiEGtX83waJj9o1chI+zK4m4Uas7w8QypBNxqsbPO6P2awVx+wKvvP5ilRBNJWvCPEYKVSbyMpdBV18953VMEv2p81U/Pj+2xgxBPIIltaKYONuS+FAuasv2x7PduvEMfcODiz4=,iv:5xPi+u9xd9P1br7yUlJn3b7sLhkhLR4YDZ9CesZIonY=,tag:RW9pi58Fa/F4O2sUhzh1iQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
