apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-vandelocht-uk
  namespace: authelia
spec:
  secretName: auth-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "auth.vandelocht.uk"
  dnsNames:
  - "auth.vandelocht.uk"
