apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  namespace: authelia
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.vandelocht.uk`)
      kind: Rule
      services:
        - name: authelia
          port: 80
  tls:
    secretName: auth-vandelocht-uk-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-vandelocht-uk
  namespace: authelia
spec:
  secretName: auth-vandelocht-uk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "auth.vandelocht.uk"
  dnsNames:
  - "auth.vandelocht.uk"
