apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/authelia
  - users-database.yaml
  - ingressConfig.yaml
  - smtp-secret.yaml
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
