apiVersion: batch/v1
kind: CronJob
metadata:
  name: pihole-nebula-sync
  namespace: pihole
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pihole-nebula-sync
              image: ghcr.io/lovelaze/nebula-sync:v0.11.1
              env:
                - name: PRIMARY
                  value: "https://192.168.178.2|$(PIHOLE_PASSWORD_LXC)"
                - name: REPLICAS
                  value: "http://pihole-web|"
                - name: FULL_SYNC
                  value: "true"
                - name: RUN_GRAVITY
                  value: "true"
                - name: CLIENT_SKIP_TLS_VERIFICATION
                  value: "true"
              args:
                - "run"
              envFrom:
                - secretRef:
                    name: pihole-nebula-sync-env
          restartPolicy: Never
