---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  type: "oci"
  interval: 5m0s
  url: oci://code.forgejo.org/forgejo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: forgejo
      version: "12.5.2"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: forgejo
      interval: 12h
  values:
    #   resources:
    # # We usually recommend not to specify default resources and to leave this as a conscious
    # # choice for the user. This also increases chances charts run on environments with little
    # # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #     limits:
    #       cpu: 100m
    #       memory: 228Mi
    #     requests:
    #       cpu: 100m
    #       memory: 128Mi
    persistence:
      # storageClass: "longhorn-crypto-per-volume"
      enabled: true
    redis-cluster:
      enabled: false
    redis:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    gitea:
      admin:
        existingSecret: forgejo-admin-secret
        email: jan@vandelocht.uk
      config:
        # log:
        #   LEVEL: Debug
        server:
          ROOT_URL: https://git.vandelocht.uk
        service:
          DISABLE_REGISTRATION: true
          SHOW_REGISTRATION_BUTTON: false
          REQUIRE_SIGNIN_VIEW: true
          ENABLE_MIGRATION: true
          MIGRATE_PLAIN_HTTP: true
          MIGRATE_SSL_NO_VERIFY: false
          MIGRATE_RESPONSE_TIMEOUT: 60
        repository:
          ENABLE_PUSH_CREATE_USER: true
        database:
          DB_TYPE: postgres
          HOST: forgejo-postgres-cluster-rw
          NAME: forgejo
          USER: forgejo
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
      additionalConfigFromEnvs:
        - name: FORGEJO__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-cnpg
              key: password
    service:
      type: ClusterIP
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres-cluster
  namespace: forgejo
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-cnpg

  storage:
    # storageClass: "longhorn-crypto-per-volume"
    size: 10Gi
  monitoring:
    enablePodMonitor: true
