---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  type: "oci"
  interval: 5m0s
  url: oci://code.forgejo.org/forgejo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: forgejo
      version: "10.1.x"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: forgejo
      interval: 12h
  values:
    persistence:
      storageClass: "longhorn-crypto-per-volume" 
      enabled: true
    redis-cluster:
      enabled: false
    redis:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    gitea:
      admin:
        existingSecret: forgejo-admin-secret
        email: jan@vandelocht.uk
      config:
        # log:
        #   LEVEL: Debug
        server:
          ROOT_URL: https://forgejo.vandelocht.uk
        service:
          DISABLE_REGISTRATION: true
          SHOW_REGISTRATION_BUTTON: false
          REQUIRE_SIGNIN_VIEW: true
        database:
          DB_TYPE: postgres
          HOST: forgejo-postgres-cluster-rw
          NAME: forgejo
          USER: forgejo
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
      additionaConfigFromEnvs:
        - name: GITEA_DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-cnpg
              key: password
    service:
      type: ClusterIP
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres-cluster
  namespace: forgejo
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-cnpg

  storage:
    size: 1Gi

