---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  type: "oci"
  interval: 5m0s
  url: oci://code.forgejo.org/forgejo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: forgejo
      version: "15.0.1"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: forgejo
      interval: 12h
  values:
    strategy:
      type: Recreate
    gitea:
      admin:
        existingSecret: forgejo-admin-secret
    persistence:
      enabled: true
    service:
      ssh:
        type: LoadBalancer
        annotations:
          metallb.io/allow-shared-ip: "share 192.168.178.155"
          metallb.io/loadBalancerIPs: 192.168.178.155
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: git.vandelocht.uk
          paths:
            - path: /
              pathType: Prefix
              port: http
      tls:
        - secretName: git-vandelocht-uk-production-tls
          hosts:
            - git.vandelocht.uk
  valuesFrom:
    - kind: Secret
      name: values-forgejo-secret
      valuesKey: values.yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres-cluster
  namespace: forgejo
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-cnpg
  storage:
    size: 15Gi
  monitoring:
    enablePodMonitor: true
