---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  type: "oci"
  interval: 5m0s
  url: oci://code.forgejo.org/forgejo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: forgejo
      version: "14.0.2"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: forgejo
      interval: 12h
  values:
    gitea:
      additionalConfigSources:
        - secret:
            secretName: database-forgejo
      admin:
        existingSecret: forgejo-admin-secret
    persistence:
      enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: traefik-external
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: forgejo.lan.vandelocht.uk
          paths:
            - path: /
              pathType: Prefix
              port: http
      tls:
        - secretName: forgejo-lan-vandelocht-uk-production-tls
          hosts:
            - forgejo.lan.vandelocht.uk
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres-cluster
  namespace: forgejo
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-cnpg
  storage:
    size: 15Gi
  monitoring:
    enablePodMonitor: true
