apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podmonitor.yaml
  - servicemonitor.yaml
  - prometheus-rules.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - dashboards/ceph-cluster.json
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
      - dashboards/traefik-official-standalone-dashboard-rev9.json
      - dashboards/velero.json
      - dashboards/proxmox.json
      - dashboards/metallb.json
      - dashboards/kube-overview.json
      - dashboards/pvc-stats.json
      - dashboards/cert-manager.json
      - dashboards/kube-cluster-default.json
      - dashboards/telegraf-system.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
