---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: keycloak
spec:
  type: "oci"
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: keycloak
      version: "25.1.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: keycloak
      interval: 12h
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: keycloak.vandelocht.uk
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: traefik-external
    # adminIngress:
    #   enabled: true
    #   ingressClassName: traefik
    #   hostname: keycloak.lan.vandelocht.uk
    #   tls: true
    #   annotations:
    #     kubernetes.io/ingress.class: traefik-external
    #     cert-manager.io/cluster-issuer: letsencrypt-production
  valuesFrom:
    - kind: Secret
      name: values-keycloak-secret
      valuesKey: values.yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres-cluster
  namespace: keycloak
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-cnpg
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
