---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: keycloak
spec:
  type: "oci"
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: keycloak
      version: "25.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: keycloak
      interval: 12h
  values:
    # Resource configuration to prevent OOM kills
    resources:
      limits:
        memory: "2Gi"
        cpu: "1000m"
      requests:
        memory: "1.5Gi" 
        cpu: "500m"
    
    # JVM configuration for better memory management
    extraEnvVars:
      - name: JAVA_OPTS_APPEND
        value: "-Xms1024m -Xmx1536m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    
    # Enable startup probe and adjust other probes
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
    
    # Adjust liveness probe to work with startup probe
    livenessProbe:
      enabled: true
      initialDelaySeconds: 0
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 3
    
    # Adjust readiness probe to work with startup probe  
    readinessProbe:
      enabled: true
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: keycloak.vandelocht.uk
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: traefik-external
    # adminIngress:
    #   enabled: true
    #   ingressClassName: traefik
    #   hostname: keycloak.lan.vandelocht.uk
    #   tls: true
    #   annotations:
    #     kubernetes.io/ingress.class: traefik-external
    #     cert-manager.io/cluster-issuer: letsencrypt-production
  valuesFrom:
    - kind: Secret
      name: values-keycloak-secret
      valuesKey: values.yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres-cluster
  namespace: keycloak
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-cnpg
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
