---
apiVersion: v1
kind: Namespace
metadata:
  name: hibiscus-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hibiscus-server
  name: hibiscus-server
  namespace: hibiscus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hibiscus-server
  template:
    metadata:
      labels:
        app: hibiscus-server
    spec:
      hostname: hibiscus-server
      containers:
        - env:
            - name: DB_ADDR
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DRIVER
              value: mysql
            - name: DB_NAME
              value: hibiscus
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hibiscus-mysql-secret
                  key: mysql-password
            - name: DB_USERNAME
              value: hibiscus
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hibiscus-password-secret
                  key: password
            - name: USE_SSL
              value: "false"
          image: docker.io/janvandelocht/hibiscus-server:v2.10.20
          name: hibiscus-server
          ports:
            - containerPort: 8080
          # resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hibiscus-server
  name: hibiscus-server
  namespace: hibiscus-server
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hibiscus-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mysql
  namespace: hibiscus-server
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2024-08-10T19:56:47Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: hibiscus-mysql-pvc
  namespace: hibiscus-server
  resourceVersion: "1940679"

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-crypto-per-volume
  volumeMode: Filesystem
  volumeName: hibiscus-mysql-pvc
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
