---
apiVersion: v1
kind: Namespace
metadata:
  name: hibiscus-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hibiscus-server
  name: hibiscus-server
  namespace: hibiscus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hibiscus-server
  template:
    metadata:
      labels:
        app: hibiscus-server
    spec:
      hostname: hibiscus-server
      containers:
        - env:
            - name: DB_ADDR
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DRIVER
              value: mysql
            - name: DB_NAME
              value: hibiscus
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hibiscus-mysql-secret
                  key: mysql-password
            - name: DB_USERNAME
              value: hibiscus
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hibiscus-password-secret
                  key: password
            - name: USE_SSL
              value: "false"
          image: docker.io/janvandelocht/hibiscus-server:v2.10.20
          name: hibiscus-server
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /hibiscus-server
              name: hibiscus-server-claim
          # resources: {}
      restartPolicy: Always
      volumes:
        - name: hibiscus-server-claim
          persistentVolumeClaim:
            claimName: hibiscus-server-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hibiscus-server
  name: hibiscus-server
  namespace: hibiscus-server
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hibiscus-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hibiscus-server-claim
  namespace: hibiscus-server
spec:
  storageClassName: "longhorn-crypto-per-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mysql
  namespace: hibiscus-server
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: hibiscus-server
spec:
  timeout: 30m
  interval: 60m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      version: "12.3.3"
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: hibiscus-server
      interval: 12h
  values:
    global:
      defaultStorageClass: "longhorn-crypto-per-volume"
    auth:
      existingSecret: hibiscus-mysql-secret
      database: hibiscus
      username: hibiscus
    primary:
      service:
        type: LoadBalancer
    networkPolicy:
      enabled:
