---
apiVersion: v1
kind: Namespace
metadata:
  name: hibiscus-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hibiscus-server
  name: hibiscus-server
  namespace: hibiscus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hibiscus-server
  template:
    metadata:
      labels:
        app: hibiscus-server
    spec:
      hostname: hibiscus-server
      containers:
        - env:
            - name: DB_ADDR
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DRIVER
              value: mysql
            - name: DB_NAME
              value: hibiscus
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hibiscus-mysql-secret
                  key: mysql-password
            - name: DB_USERNAME
              value: hibiscus
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hibiscus-password-secret
                  key: password
            - name: USE_SSL
              value: "false"
          image: docker.io/janvandelocht/hibiscus-server:v2.10.20
          name: hibiscus-server
          ports:
            - containerPort: 8080
          # resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hibiscus-server
  name: hibiscus-server
  namespace: hibiscus-server
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hibiscus-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mysql
  namespace: hibiscus-server
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: hibiscus-server
spec:
  timeout: 30m
  interval: 60m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      version: "11.1.14"
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: hibiscus-server
      interval: 12h
  values:
    global:
      defaultStorageClass: "longhorn-crypto-per-volume"
    auth:
      existingSecret: hibiscus-mysql-secret
      database: hibiscus
      username: hibiscus
    primary:
      service:
        type: LoadBalancer
      persistence:
        existingClaim: hibiscus-mysql-pvc
      # configuration: |-
      #   [mysqld]
      #   authentication_policy='* ,,'
      #   skip-name-resolve
      #   explicit_defaults_for_timestamp
      #   basedir=/opt/bitnami/mysql
      #   plugin_dir=/opt/bitnami/mysql/lib/plugin
      #   port=3306
      #   mysqlx=0
      #   mysqlx_port=33060
      #   socket=/opt/bitnami/mysql/tmp/mysql.sock
      #   datadir=/bitnami/mysql/data
      #   tmpdir=/opt/bitnami/mysql/tmp
      #   max_allowed_packet=16M
      #   bind-address=0.0.0.0
      #   pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      #   log-error=/opt/bitnami/mysql/logs/mysqld.log
      #   character-set-server=UTF8
      #   slow_query_log=0
      #   long_query_time=10.0
      #
      #   [client]
      #   port=3306
      #   socket=/opt/bitnami/mysql/tmp/mysql.sock
      #   default-character-set=UTF8
      #   plugin_dir=/opt/bitnami/mysql/lib/plugin
      #
      #   [manager]
      #   port=3306
      #   socket=/opt/bitnami/mysql/tmp/mysql.sock 
    networkPolicy:
      enabled:
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: longhorn-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
  namespace: hibiscus-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

