apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup
  namespace: velero
spec:
  schedule: 0 */10 * * *
  skipImmediately: false
  template:
    volumeSnapshotLocations:
      - minio
    csiSnapshotTimeout: 30m
    hooks: {}
    includedNamespaces:
    - '*'
    itemOperationTimeout: 30m
    metadata: {}
    ttl: 0s
  useOwnerReferencesInBackup: false
