apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup
  namespace: velero
spec:
  schedule: 0 */10 * * *
  skipImmediately: true # skips the firsf snapshot after creating of velero schedule.
  template:
    hooks: {}
    includedNamespaces:
      - "*"
    itemOperationTimeout: 30m
    metadata: {}
    ttl: 0s
  useOwnerReferencesInBackup: false
