apiVersion: v1
kind: Secret
metadata:
    name: filen-cli-claim
    namespace: filen-cli
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:PDBa9rglywSS1qGBCHu+tXtt4PqmcWVurRck2PUBJVzjy6iSEfRsR7n/Ol4=,iv:thEfkLMelJeczB7+xyNXZzf1pSM4O7tZU00ryqePiFU=,tag:nWpiOA538Bc0egawjjyk7Q==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:1F3K0elI,iv:QRoOztJWNCulKBO/H/DQtFvkjISAT92mZMDXa58rFpo=,tag:/v3cjzv2BxqGSKNK0f7nSg==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:hHlzQXShPEzHw3tDnihC,iv:UvEGUzB/9+083YUaCJSAE8kpsda+1R+3tlN+NslBK0M=,tag:YjpOcO7WYsG4gU7Lthy9Jw==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:HEfp3/yO,iv:ZaychN0ALg0s4/vIG/SyyDYmYQAuTi27k/QqoFNWvsc=,tag:JWKAsE0WRJnUViWxoEk4yQ==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:fFRc,iv:jS/LMwLWEnthgWW1ZVAiV1Gva37uuuacbS2d35CDdoI=,tag:SDGqrZitq3bEeXNM88U6Ag==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:wpKDd9GyKQ==,iv:oypUzy80Wew7zMxTxmG5ugcJzG8cf4qaim8vAUl26Aw=,tag:gW28/LsHztgxibin7Kj/Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGREk2NWs4R0tLekxKTlR3
            bTErbnI4ZjM0V0NYZ1dQYUxUMDQ3RWdnUzFBCjJBaTRrLzFxeXhpN21wQXgwZFJk
            NlV0N3R4TXllV1dYNDg5QVpneVBMS0EKLS0tIFVkbzZCYUl4cXlGcHNLZVI2Rlo1
            TWdNR1hiNE9LTjdUSXhvRXlya3FtdVUKMSmM0tz0xZqk4x4Bvu43RZn5LydGFAz3
            OsfmVNH6nK26Cs5lfM0BbpBWhqi2nWuu5OE3JO5uJ2m4raLa4+9d8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T21:19:36Z"
    mac: ENC[AES256_GCM,data:4Nw7fAQfyOeVDYy7l4HXokxPbZ8TjNTW/gUCoIqsrvkFW+ageYLCPaA8nlo0Xbzelwv5BEG3qX29Fg3VGgu2Ods8SMlTGKxq30h7rhbJ4pvlnFJeiQu9E53T0Kh+AuVin/YM5/I3pGoUFWM4/ikQESE+iT2ykdzxjmmQW4HYXSU=,iv:Y4qWGGXUMuAHSXcQeeWfPQwKnbdZaS+2suYqPP4jJ9Q=,tag:d3ZN2zxwIXyrPatg4Q83Ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
