apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/filen-cli
  - filen-cli-secret.yaml
  - filen-cli-webdav-claim.yaml
  - filen-cli-s3-claim.yaml
patches:
  - path: patch.yaml
    target:
      kind: Deployment
