apiVersion: apps/v1
kind: Deployment
metadata:
  name: filen-cli
  namespace: filen-cli
spec:
  template:
    spec:
      containers:
        - image: filen/cli:v0.0.31
          name: filen-cli-webdav
        - image: filen/cli:v0.0.31
          name: filen-cli-s3

