apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/velero
  - velero-secret.yaml
  - velero-filen-secret.yaml
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
