apiVersion: v1
kind: Secret
metadata:
    name: velero-secret
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:dpe/lRvU+s2NbpTub7RuT4u3xhzaOQnK697UruhqIgQDqeITcPrb4Wjc5QEnoc4z03KbxBhXj7Xizw2sIxkwLCqCS5ZKvhFnPwsoH4HzPQ2fS1eQZVoGFl/3cTjKwqN/2GbJ,iv:vQkietis6D/n1zc+UykqwzACZTs1k86uw9sQwkoElOU=,tag:9WFb1EHOC7l7CnvcJc7NWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VTNRNlREbko2WE05L05n
            L3hrQzZpcGNXYUR5V25sVS9mZzcxbUtieWxRCk5LSHZnRDlYT0lsaTh0eTFaS1Vh
            cElPbUdGTk9nbXQrdEFWS1dIemhMSFkKLS0tIDZHL3FWOTZOU2FOUDlPTE8xUFdN
            SFRwaTdyWVRIYm81djlsVnJSY0VRcTQKybDIrLikx4xknKb2o4ppwrM0H++CZhVk
            4OAe79NXoPPJ5tSkcaYxo+INjHn++MqWz+yUqk4BPKhR6ux3qrOaeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T12:30:08Z"
    mac: ENC[AES256_GCM,data:LSmmc3eVm/SW7zOodIo8FLbafiNH2Xo8GtO4CqcAh1+DNroHOhZRB2trgRHEG9w8yEO4Xp+zFhKBmmlOcZALUNlzgHLrpKSXJpAdz+NIXn+5z4KgHjjiU5d4K5fq1zWsAoBjJQ3ilTw8lMzP15wqe+32gOkNoH/HORfV9C7IoL4=,iv:REeZb0zC1zUVdinsHgR6F1Cam5aYk6J7o3mUoBn621o=,tag:U8qiwmconoVCnp1P7f7XKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
