apiVersion: v1
kind: Secret
metadata:
    name: velero-secret
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:JfBBdBFmdG5QazaN5e6x68W1Xqo8I0iWblZTweGv/mpsHbOsDyBGOLBmwTw8x7+/QtpK8Bv7WipsJgHKPZifo+1iimmHmcTW8lPLBknNk+KtLcL8DsN0keaYcVNxN7bF13MmOCCHfw6iJnzuyEbOYw==,iv:4KgilXtRRjnPIz2kGPWt59mcNBUZP9mh1zNbSgV23I0=,tag:G4xnJezerD9vK4HJdh4XCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UllpT1R1ajFFK2VuVmlE
            OHNxUktTTnpvbFZVWFN4UXNXK2l4TGI1amtrCmwycjBxWnpKY2t4ZG8rLzBYRThk
            bFdrV3pmdGVLRktacUU5ajhYajdCS1EKLS0tIHN0WkcwT2dJL1VyS2lKcjI5Z3RE
            cy9Jc0hkeG93MHN4Mkp2NFRwaDh6cEkKufwGzGOHCbsdW0XSmsGLiKNuM7nyQx02
            zj50EJQuCo4EPgL2DuVuLYkjXEMD2S5BMpqhMoVYqj1D5gO7F/Nqeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T17:03:50Z"
    mac: ENC[AES256_GCM,data:ecgeAg3kc1nh/j+4sACQ/SrI+RfpbkmHA4Hrd1PU+ZBxV2oyjfH2nc/fNSRBFzrPMwOaHXfVb7hY1CGVEClTpUpWmS6bimBHvUatYOJvbX26K+eEeh+pnhjuEwhrc48YSnsnoTeaRfgvNH/l1oySiVsZCJYD4z8pdNUT1TXtevo=,iv:PYb0OR70TPlVcMZCg4g19bGGvKaG4Pbxu8PPROw9ITo=,tag:TVKFarYzJaNWHhHndw1vKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
