apiVersion: v1
kind: Secret
metadata:
    name: velero-secret
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:6GfhK8tDUvDHw3J8QtaDoyvau4pzVG3MO/4ldKZqwWm8UAUyL6Q/ONUS6wzQjrjJJPTFkQZKy3yY1OS4ulYlYhu3HuEEOwk/CYLAFz57Y05CtFm5kVYRViRp1EfWOK1lY7Z0HIbA+jJsAF7hC4yxYg==,iv:M5VwTf9BNQT+LDxKxSwA45PR6QIQnVsaT+En4OsXK0c=,tag:TC8U7TzpQy+pjNdRaXvfMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMS9NZHIzcVdJK3NiT1Nt
            dGRQQ3psajRMTmFhTmZCS1pZdlhRSEVQTDJvClVDb1BteFRFRlRONG5kZXVRVTVT
            cmovQlpYaWovcXZIWjVaN1NxVHFIR00KLS0tIEVSY1FFYTk2MlRUc2V3em9VZjdN
            NEpoSk12YlZIZnFoa2tncm5qVmVaUkUKPOAhMK4i2pzjvRCsIPb4WTHtppnl4zuQ
            UB6VI46bJ7NMtYrqrP21JRb6LD3wrpT1BOGKbK3J01XOe4qkhfAkGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T19:38:54Z"
    mac: ENC[AES256_GCM,data:gFASwhnloBVcjQ9YzAiN8JL7KG7CSnyfrG9L47UFr69T4e88pDpJYieJZgDDN2N0IMAQPOE2vBYwx8ATQZnZPslZq5ph+598c2y7Z89IK8JZYWMkqUdq7b6W08LkKCAWdo0Dvex/rdnM0iN+2YeoB3ioGOpnspsCR0VrxRvM720=,iv:SE0XaAVErYjbW6W4QMlVXbcu3cbApnP0f6xNSgQm/+8=,tag:Y6uC0TY5EGvlDEmltKAZ1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
