apiVersion: v1
kind: Secret
metadata:
    name: velero-filen-secret
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:NnYdG5IvMcxwSEdi9VWfLSnixkrF61iDF2OGei5nUsy0cJrqJwkpWC9KZlbPQPvnbMauJ5rCucyNj3zZ6Mir2bZTne61scRDwWVjUgzC21T/H+BbCJSa2l7iu22Vj2XwmQ==,iv:tsvn3n+cZ/GAQ30rpHBvbVwCE1Y8QfHTrTnm4ioA1PY=,tag:u8qN4oHfKmAEueJ0us7ckg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMDZVNzh0aWQ2eit5Tkc2
            NTlhVThQNlVMMDFuRnpZSUY3b255OXA2S2xvClh3MkNPT29Jb1EvTU11Y2FwZmo4
            cFROZHF4UmExbElBbEVvTGpnVXo0QjgKLS0tIFA2N0l2MjVWam5mK2hOeWFRSzRj
            anJyNFlqL05mZ2NEYVR6MzBIUzd5ZDQKZgHKYQuaq0vH6Wi1rE8Hyx2HuUWEFwCn
            0502PvVEmP20+jdjVQN2FFYWRzgjUJR3LAJQB1FhsE1lMVSe7nmJ8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T16:56:38Z"
    mac: ENC[AES256_GCM,data:ctuPuAPiD1zgo8T8dGsXQvvkyKq7xM7jYH88NOKC5aB/DNwpQsFA158vl9Se76EhqZb6wLnkI6eDuNAi1aFfNdNJ60zZW/7YgPTItKt2LERuVei8ph5mqzJHqf91CFBW6h1306/cMXQSoN4YxmpcQq681fJT0Z8De9KKcure7Y4=,iv:tMmOziNWX9dRsi3eQKvlwbIbHxgZ38Cpfzy8DERNsIU=,tag:dVWjB0lWzVHqVdvShiD/1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
