apiVersion: v1
kind: Secret
metadata:
    name: velero-secret
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:4TBtsL8MqpRajfltJvQhBAGCkjA4wS7lP5PCCYTKiajyRUUuw3G4zXXNw8NAVEn1twYrO0fdlzoYfWxbnmUxZIH4cT6r8KD3ei/uyMWJo2l8EjWNeGjZPwrC99YIz0NmqtBH,iv:DcxBk21ZUX2ExPKtcu5lmk6lPEFNdEPP4zrjBgV6k1M=,tag:XA8/IVxTu1l3O0XuvIFyLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT3V1NjFCTmJieTF3REV5
            VndTcHFSWTBSNlNFT3g2WFNnSDlBZG5IRjBzClRjL0NDVTNMcjBVT3p3RE9RN0JY
            YnpOUTNIQUxvYWtWeGdTUStCT0FvTFUKLS0tIGJRenFtSjkrakxmbVgwK2lQdXhX
            WHVEb0JFeHl5bmlqdmVsK2o2RTZXK0UKXSHq2+WaQINsmk871OgA15RNM0jqqsye
            nuEPyhWn3C6BSybkVmOC68Jf7PAk/p4804ZsldMbcICbYOGmtHytwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T19:45:42Z"
    mac: ENC[AES256_GCM,data:n13oOYl1hEbWskpdTGeZ7csOu57SNGNACVktRGjBtz8eOLtchXcGnKJyP5Xfo4LsrmJRHAzoUVGUUaPbhlzSR8przgVXndOyCaPYJ6tRlbNoOV+h+JLfT2o962SZyspkT1aeixaHMlHBNv35F8ZrOqXyU3bt1Rp05S2ZJS3OwXE=,iv:ztfLkJmNnjqxcquSBhKsaVQfPjEwISEDZ2zyvVjPsTA=,tag:nJC93d7XYbazzWzyvLj2Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
