---
apiVersion: v1
kind: Namespace
metadata:
  name: searxng
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubitodev
  namespace: searxng
spec:
  interval: 5m0s
  url: https://charts.kubito.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  timeout: 15m
  interval: 30m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: searxng
      sourceRef:
        kind: HelmRepository
        name: kubitodev
        namespace: searxng
      interval: 12h
