apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest.yaml
secretGenerator:
  - name: values-openwebui-secret
    namespace: openwebui
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
