apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:1JQlgKpFqhVeq4ypl266ezul2NYMbizjl84/+H9xb/bRhqPBIE4ULw==,iv:WG+61ws4QJCJXLCOHv66qB/s1cZ2gdXbAXh1/q8f6SQ=,tag:1IhAmm1OPmQp7BIGtti3Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epjlv060j8z57f7vm8jvwfl0zqz9wjtw0cga5vpgw0upwa0nsdrshdn3ku
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaLzNvNFRUU1hnWHdLSVJ5
            M1ZsRXI3Z0lvc1hacDBubUZFWjAwVVZNQUdvCkNjMlVFdjN5OHFQOUNLY2RUbVZH
            cEVubzdmd3Q0LzVQaHZZWWRZN1k2NnMKLS0tIG1XN1ZPdk1LVFVsK0tMczE3YUNt
            am1BaW5HZFhzY2MzMnJhajBka2NQNjgK8tG70kkUIlIqYd55ZbmiN4ixzrwKFWcu
            7FIp5jkwLer2VIHtL6ExvY3tUkphUAOpSzBYVaf3q6g1jId5i4uq7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T13:01:47Z"
    mac: ENC[AES256_GCM,data:qxHpijxtTmsaQFlEgPYPYQi8tz/jFwkS/shj4cRF1uOsbHcaM6VaEEnHsbNRGINmizEqy5OkNIoJQMw0uA/tO+k/sEBFGxSpOEdX95hoJAyzFhML80D1dgQ/85fbAy/EC4hz01320QtH0x3ZcASxwey2VFRiYzXxFG4U6+/6n80=,iv:xHGTZPUMFU9HFalDB9ReZiafql7ddZviArKzT1DfPUA=,tag:AZw0cz8oy+zO381Ue41yZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
